### ISSUE TITLE
Add generation of QC report to scpca nextflow pipeline

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#1]
After the counts matrices are obtained for each sample, we will want to generate a QC report. We will want to add a process to the nextflow pipeline that takes the counts matrices (or `SingleCellExperiment` objects) as input and outputs a QC report.

**Comment by jashapiro** [comment]
Functionally blocked by updates to scpcaTools to support taking two SCE objects.
