### ISSUE TITLE
Add parameter checks to main workflow

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#105]
To aid in usability as we prepare for external users, we could add some parameter checks to the main workflow to give more informative errors if certain parameters are improperly set.

For many of these, we might check that files exists/are accessible. That might look something like the code below:

```nextflow
param_error = false

// repeat blocks like this for each file to check, or create a loop to check a series of expected files
if(!file(params.infile).exists()){
  param_error = true
  log.error "The file '${params.infile}' can not be found."
}

// after all checks
if(param_error){
  System.exit(1)
}
```

For parameters which have specific values, we might add other checks. I have some concern about separating the default values from the check, but I think it likely worth the effort.

**Comment by jaclyn-taroni** [comment]
We'll set this for this sprint, but it's a nice to have not a must have. It should be the last thing we pick up!

**Comment by jashapiro** [comment]
One thought on this is that we may want to think about having some parameters, such as  `run_metafile` and `outdir` set as blank by default, to prevent external users from getting cryptic errors if they do not set them and their run tries to access our files/locations for which they do not have permission. 

We could then set these values within a `ccdl` profile block, such that we would invoke them with: `-profile ccdl`, or more likely with `-profile ccdl,batch`, as you can include multiple profiles, comma separated.

Not quite as easy as using them by default, but not bad, and could save external user confusion.
