### ISSUE TITLE
scpca-nf user instructions: metadata file section

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#110]
As part of the user instructions for `scpca-nf`, we will need to update the section on creating a metadata file. This section should detail the necessary columns needed in the metadata file and instructions on what to include in each column. 

This should also include instructions on how to obtain `scpca_run_id`, `scpca_sample_id`, and `scpca_library_id`. As discussed in our planning meeting, right now we plan on telling users to use a set of ID's that we provide and based on user feedback and how frequently others are using this we may adjust this approach. 

These instructions should be included as a branch on the branch `allyhawkins/outline-scpca-nf-instructions` from #106 so we can merge all the instructions together.

**Comment by jashapiro** [comment]
Just a note that this will not need to have every field in our library file. The only fields the workflow looks at are defined in main.nf:
https://github.com/AlexsLemonade/scpca-nf/blob/3c1004dee87df56618f57308c5a3c0868a1b72bc/main.nf#L45-L62

Notably absent are things like the submitter_id, alt_ids and md5 files.

**Comment by jashapiro** [comment]
Looking at this again. We don't actually use the `files` field in the pipeline anymore. I'm going to remove it from that initial step, so that we should be able to leave it out in the example metadata file.

**Comment by allyhawkins** [comment]
Just noting that we do use it in the spaceranger workflow so we should address that you will need to add it when we add the spaceranger section in #114.

**Comment by jashapiro** [comment]
> Just noting that we do use it in the spaceranger workflow so we should address that you will need to add it when we add the spaceranger section in #114.

Oops, I missed that. Never mind!
We might say that filling it in isn't required unless using spaceranger. Longer term, we might see if we can remove that dependency and just get the file list programmatically as we do elsewhere.

**Comment by jashapiro** [comment]
closed by #118
