### ISSUE TITLE
scpca-nf user instructions: setting up a config file

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#112]
The user instructions for `scpca-nf` should include a section on how to set up your own config file. This is currently divided into two sections in #106, setting up a profile and adjusting parameters. Both of these sections should be addressed so users are able to set up their config file. 
We will also provide a template config file, #111, that can be referenced and instructions on what should be edited in this template file should be included in this section. 

These instructions should be included as a branch on the branch `allyhawkins/outline-scpca-nf-instructions` from #106 so we can merge all the instructions together.

**Comment by jashapiro** [comment]
closed by #121
