### ISSUE TITLE
scpca-nf user instructions: AWS Section

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#113]
We should include some guidance on how to use `scpca-nf` with AWS. 
This will probably only include some basic information on how you could use AWS with some guidance to reach out to someone for help as this can be complicated to setup. 

These instructions should be included as a branch on the branch `allyhawkins/outline-scpca-nf-instructions` from https://github.com/AlexsLemonade/scpca-nf/pull/106 so we can merge all the instructions together.

**Comment by jashapiro** [comment]
closed by #120 (why is automatic closing not working?)
