### ISSUE TITLE
scpca-nf user instructions: expected output

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#116]
In addition to the information about running the workflow that we already have sections for, we should include a section about the output files that will be generated.

This should include an example directory tree, and a description of the difference between `internal` and `publish` directories.

More detailed information about the SCE objects themselves can be handled by a link to the main docs site.

This may also include a brief explanation of how `internal` files may be used as checkpoint starting points, and the `--skip_mapping` option?

These instructions should be included as a branch stacked on the branch allyhawkins/outline-scpca-nf-instructions from https://github.com/AlexsLemonade/scpca-nf/pull/106 so we can merge all the instructions together.

**Comment by allyhawkins** [comment]
Closed by #124.
