### ISSUE TITLE
Remove `files` as required input field for spaceranger

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#117]
In the interests of making the workflow easier to use and more robust, we might not want to require a list of input files in the library metadata file. For most modules, we get the lists of files programmatically from the contents of `files_directory`, and we _ought_ to be able to do that for spaceranger too.

>> Just noting that we do use it in the spaceranger workflow so we should address that you will need to add it when we add the spaceranger section in #114.

> Oops, I missed that. Never mind!
> We might say that filling it in isn't required unless using spaceranger. Longer term, we might see if we can remove that dependency and just get the file list programmatically as we do elsewhere.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/scpca-nf/issues/110#issuecomment-1057268369_

**Comment by jashapiro** [comment]
A note on implementation: We should be able to modify the `getCRsamples` function to take the files directory rather than a string of files, then use 
`file(files_dir).list()` to in place of the `tokenize` call we currently use.

See:  
https://www.nextflow.io/docs/latest/script.html#list-directory-content

**Comment by allyhawkins** [comment]
Closed by #139.
