### ISSUE TITLE
Move ccdl-specific parameters to a profile

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#123]
We may want to think about having some parameters, such as  `run_metafile` and `outdir`, set as blank by default, to prevent external users from getting cryptic errors if they do not set them and their run tries to access our files/locations for which they do not have permission. 

We could then set these values within a `ccdl` profile block, such that we would invoke them with: `-profile ccdl`, or more likely with `-profile ccdl,batch`, as you can include multiple profiles, comma separated.

Not quite as easy as using them by default, but not bad, and could save external user confusion.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/scpca-nf/issues/105#issuecomment-1059494399_

**Comment by jaclyn-taroni** [comment]
Is `Closes` (temporarily) broken? 🧐  Closed by #136.
