### ISSUE TITLE
Update documentation with resource requirements

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#153]
We should provide an initial strong caution in the docs about the resources that are needed for running the pipeline. Currently for alevin-fry we need at least 12 cpus & 24 GB of RAM (though 2X that if a run fails for any reason). 

This means that running locally is _possible_ but only on a fairly well-specced machine (not most laptops).

We should probably remove any references to running the workflow _without_ setting up a profile, as that is just setting people up for failure.

As we address questions in #151, we might be able to rescope a bit (fewer cpus is possible, but probably not less RAM?), but the warning should remain.

**Comment by allyhawkins** [comment]
Closed by #171
