### ISSUE TITLE
Restructure README so link to setup externally is easy to spot

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-nf#156]
The link to setup externally is currently under setting up. In order to make it clear that there are instructions for two types of users (external and Data Staff), I propose the following structure

**scpca-nf**
[same content]

**Running scpca-nf in your HPC environment** (want to be a bit more descriptive than external user, what qualifies someone as an external user?)
Say a bit more about what that entails and link to the doc. I'm not sure if we should put the command here (in the interest of not misleading users to think that this is a quick and easy setup)

**Running scpca-nf for the Data Lab Staff**
same content, without external stuff under Running scpca-nf for the ScPCA portal

**Comment by allyhawkins** [comment]
Closed by #167.
