### ISSUE TITLE
Restructure instructions for external users so it doesn't seem like it's quick

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-nf#157]
In the intro, the amount of work involved before they can run the command is kinda minimized. I think we should:
- In `How to use scpca-nf as an external user`
   - Expand on what file organization means and then link to File organization section
   - Expand on what creating a metadata file means and link to metadata file section
   - Expand on what config file means and link to config file section
   - Then show them the command. I also think there were different variations of running the commands, which went over my head. but I think we should link them here.
   - Talk about the output files briefly here-  maybe the show the folder structure and then link to output file structure
 

@sjspielman suggested having the different variations of commands together. (please tell me if I misunderstood)
From the last session with  @jaclyn-taroni and @jashapiro,  we wanted to remove that users could run them locally.

**Comment by allyhawkins** [comment]
Closed by #168.
