### ISSUE TITLE
Add repo description

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-nf#159]
Add repo description. We could use this as an opportunity say that the pipeline caters to both external and Data Lab users.

**Comment by allyhawkins** [comment]
Planning to add the following to the description but wanted to get input before I actually did: 

"scpca-nf is a nextflow workflow for quantifying single-cell and single-nuclei RNA-sequencing data. The workflow is also used for processing samples available on the ScPCA Portal." 

Tagging @jaclyn-taroni and @dvenprasad for any thoughts or edits.

**Comment by jaclyn-taroni** [comment]
What about:

"scpca-nf is the Nextflow workflow for processing Single-cell Pediatric Cancer Atlas Portal data"

It's significantly shorter and you can use [Topics](https://github.com/topics) to indicate the rest of what you're hoping to communicate (I'd use Nextflow as a topic as well).

**Comment by allyhawkins** [comment]
I updated the description and then added Topics that I thought were relevant. Let me know if you think there are things that are missing that we should add (or remove).

**Comment by jaclyn-taroni** [comment]
CITE-seq and spatial maybe?

**Comment by jaclyn-taroni** [comment]
I think we can feel free to close this @allyhawkins if you're happy with the description.
