### ISSUE TITLE
Alevin-fry reporting 0 cells detected for some libraries

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#174]
**Describe the bug**
In running the samples for the Mullighan and Teachey/Tan projects, many of the libraries are failing downstream steps after completing Alevin-fry, such as the steps that involve merging with CITE-seq data or filtering the object. This is because there are no cells being identified by Alevin-fry for these libraries. 

For the Teachey/tan project this was the error being reported for a handful of samples during the `make_merged_unfiltered_sce` object. I then went back to the work directory of the previous steps which was quantifying the CITE and RNA libraries with alevin-fry and saw that nothing appeared off with the CITE-seq data, however in the RNA output there was no cell barcodes identified and an empty matrix with just gene names was being produced. 
<img width="990" alt="Screen Shot 2022-04-28 at 8 57 15 AM" src="https://user-images.githubusercontent.com/54039191/165769003-fdd16a95-5d97-48c8-8c09-004e0222fe7e.png">

**To reproduce**

This occurred with multiple samples, but I particularly investigated SCPCR000692, SCPCR000064, SCPCR000704, SCPCR000602, and SCPCR000163 noting that they were all failing at the step after alevin-fry quantification because of 0 cells. I also ran SCPCR000692 through cellranger and noticed that there were no issues with the sequencing library and it successfully identified 16,000 cells. 

What command did you use to invoke the `scpca-nf` workflow?

```
nextflow run AlexsLemonade/scpca-nf \
		 -r v0.2.7 \
		 -profile batch,ccdl \
		 --project teachey_tan \
		 --outdir 's3://nextflow-ccdl-results/scpca-prod' \
		 -with-tower
```

**Expected behavior**
We would typically expect Alevin-fry to quantify the number of cells identified if the sequencing was okay, which in this case it seems like the sequencing doesn't seem to be the problem. 

**Version information**
What version of `scpca-nf` are you using, and what version of Nextflow?
v0.2.7 and Nextflow version 21.04.1

**Additional context**
I also had tried running alevin-fry with different technology thinking that may be the issue, but using 10Xv2 and/or 5 prime still resulted in 0 cells identified. In running cellranger, I confirmed that the technology version was correctly reported in the metadata.

**Comment by rob-p** [comment]
Hi @allyhawkins,

  Are these occurrences of 0 cells happening in the single-cell library or in the feature barcode library?  Also, what method is being used to determine the number of cells (e.g. knee method / unfiltered)?  One idea to look at where things may be going astray would be to see what the mapping rate it — how many mapped reads make it into the RAD file to start out with.  You can get this from the `meta_info.json` file in the `aux_info` directory of salmon's output directory. cc @DongzeHE @k3yavi.

--Rob

**Comment by allyhawkins** [comment]
Hi @rob-p, thanks for checking this out! I actually think this may have been due to an out of date version. I had checked into the percent of reads that were mapping and seen that around 60-80% of reads were mapping. This was also occurring in the RNA library but not matching CITE-seq library.  I went ahead and updated the version of alevin fry from 0.4.2 to 0.5.0 and salmon from 1.5.2 to 1.8.0 and that has appeared to work thus far. I just am testing on the remaining samples that failed the workflow to make sure that that was the only issue that we were seeing. Out of curiosity were there any major changes between those versions that could have accounted for alevin-fry being unable to identify barcodes? If we see any other weird errors crop up we will definitely be sure to ping you. Thank you again!

**Comment by allyhawkins** [comment]
@rob-p I just wanted to give you an update that updating the version appears to have solved the problem for some samples but not all of them... I still have a few samples that are reporting high mapping rates but 0 quantified cells and I'm at a loss for why. I am running those specific samples that still had 0 quantified cells even after the update through cellranger now. 
Also to answer your previous question about knee/unfiltered, we are using the unfiltered method to identify cells.

**Comment by DongzeHE** [comment]
Hello @allyhawkins, 

If possible, could you please check whether the permit list file has a single column? The last time I met this situation, I provided a two-column permit list file instead of the one-column permit list that can be recognized by alevin-fry. Alevin-fry will read each line in the permit list file as an expected cell barcode, so if there are any tabs or commas, they will be regarded as a part of the cellular barcode. 

Best, 
Dongze

**Comment by allyhawkins** [comment]
Hi @DongzeHE, we are using a file with one column containing cell barcodes. Also important to note is that we've been using the same setup of Alevin-fry and barcode file for hundreds of libraries and this is the first time this has occurred. It's only affecting a few libraries that we are processing.

**Comment by rob-p** [comment]
Hi @allyhawkins,

  Would it be possible for us to get access to one of the libraries that is giving 0 cells?  We can try to see whats going on. Presumably these are all single cell data with the same permit list, right?

Best,
Rob

**Comment by allyhawkins** [comment]
Hi @rob-p, thanks so much for offering to help debug. Yes, these are all single cell data with the same permit list. Because we have to stick to guidelines set forth in data use agreements, we are limited on what we can send. I can send over the log files from one of the runs however and maybe you guys would be able to glean some more information from those files that I might be missing. I can send those to you over slack in the workspace we had previously set up for debugging Alevin-fry. Thank you again for helping us out with this!

**Comment by allyhawkins** [comment]
Closing this with the addition of changes to add autoscaling in #190 and default use of dynamic disk #191.
