### ISSUE TITLE
[BUG] Rendering of the QC report is halted on HPC because markdown file gets placed in a read-only directory

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#208]
**Describe the bug**
If you have an error message or report that you can include, please do!

One of the users testing the pipeline was attempting to run the workflow on an HPC by submitting to a slurm job scheduler. They received the following error: 

```
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'sce_qc_report (library01)'

Caused by:
 Process `sce_qc_report (library01)` terminated with an error exit status (1)

Command executed:

 sce_qc_report.R      --library_id "library01"      --sample_id "sample01"      --unfiltered_sce library01_unfiltered.rds      --filtered_sce library01_filtered.rds      --qc_report_file library01_qc.html      --metadata_json library01_metadata.json      --technology "10Xv3.1"      --seq_unit "cell"      --genome_assembly "Homo_sapiens.GRCh38.104"      --workflow_url "https://github.com/AlexsLemonade/scpca-nf"      --workflow_version "development"      --workflow_commit "ffa384e4b69983a2a4ff563be06dc97b4b3ad5cb"

Command exit status:
 1

Command output:
 (empty)

Command error:
 Error in file(con, "w") : cannot open the connection
 Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> write_utf8 -> writeLines -> file
 In addition: Warning message:
 In file(con, "w") :
  cannot open file 'qc_report.knit.md': Read-only file system
 Execution halted

Work dir:
 /mnt/isilon/opentargets/wafulae/scpca-nf/work/df/cbe40e2cb706147a95a74c3dd19bc4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`



Tue Aug 30 13:48:04 EDT 2022
(END)
```

This error wasn't seen when the same user ran the workflow on an AWS instance. 

**To reproduce**
If possible, please provide example code to reproduce the problem, including any information about the dataset where the problem occurred, if possible.

The user had written a bash script to submit to the slurm scheduler and the filtered and unfiltered RDS files were written out successfully, but the metadata and QC reports were not created. 

What type of system are you using to run the workflow (local, slurm, AWS, etc.)?
If you are using a custom profile or config file, please include the file and settings you used.

Slurm 

**Version information**
What version of `scpca-nf` are you using, and what version of Nextflow?

They were running the `development` branch of the workflow.

**Additional context**

It looks like there is an issue with the permissions of the `qc_report.rmd` file from `scpcaTools` because it is read only. I believe that we should have to alter those permissions and then update the release of `scpcaTools` and that should fix the problem.

**Comment by jashapiro** [comment]
This was fixed by #216
