### ISSUE TITLE
Discussion: Change to always include introns?

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#214]
As of Cell Ranger 7.0, intron counts are included by default for all quantification. We should consider switching to this behavior for future compatibility. 

Currently, we quantify single-nuclei data with introns counted, but single-cell data with only exonic (and ambiguous) reads. WE could change the single-cell samples to include introns to better align with current Cell Ranger behavior. Conveniently, we have RAD files mapped against the `splici` reference for all quantifications, as that reference gave more reliable results in general. So we can requantify with no additional mapping, which should make recalculation for all samples fairly fast.

The biggest bottleneck would probably be switching our Space Ranger image to 7.0 and requantifying the spatial data, as that would require remapping. (If Space Ranger were more flexible, we could reuse the `.bam` files we already have, but I don't know that we have a good way to do that.)

If we do consider this, we will probably want to more carefully consider the implications for updating quantifications on the server. We also _may_ want to tackle #149 before we do this (which I think would require full reruns, but would save from future reruns).

**Comment by jaclyn-taroni** [comment]
I'm going to put this in the current Epic we have going just so it gets discussed alongside those issues.

**Comment by jashapiro** [comment]
A note that we may also want to update alevin-fry reading code to use [`fishpond::loadFry()`](https://mikelove.github.io/fishpond/reference/loadFry.html), which will simplify some of our code, and can allow us to keep multiple assays, should we so desire: I might propose `counts` (U + S + A), `spliced` (S + A), and `unspliced` (U); This would allow the greatest flexibility for downstream users, even enabling RNA velocity if people want to go that route.

**Comment by jashapiro** [comment]
In looking into this, it appears that Space Ranger does _not_ use introns automatically, and indeed that may not be possible, as I can't find an option in [the docs](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/count). For Cell Ranger, the option is `--include-introns`, but that doesn't seem to exist in Space Ranger. So rerunning Space Ranger files may not be needed.

**Comment by allyhawkins** [comment]
Closing this in favor of #229
