### ISSUE TITLE
Update salmon and alevin versions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#218]
In concert with #214 and #149, we should probably update Salmon to version 1.9.0. Looking at the [release notes](https://github.com/COMBINE-lab/salmon/releases/tag/v1.9.0), it looks like the primary update for our purposes is better error handling when running out of space (hopefully not an issue as much with the auto-expanding volumes), and a smaller Docker image.

Updating alevin-fry to 0.7.0 seems likely to be mostly address errors we are unlikely to encounter ([release notes](https://github.com/COMBINE-lab/alevin-fry/releases)), but upgrading in parallel seems prudent.

**Comment by jaclyn-taroni** [comment]
Put it in the Epic please if you think it should be accomplished at the same time as #214 and #149.

**Comment by jashapiro** [comment]
> Put it in the Epic please if you think it should be accomplished at the same time as #214 and #149.

I thought I did... I guess it didn't stick.

**Comment by jaclyn-taroni** [comment]
> I thought I did... I guess it didn't stick.

ZH nonsense.

**Comment by jashapiro** [comment]
Hmm... it seems that `salmon` and `alevin-fry` are no longer being updated in the [biocontainers](https://biocontainers.pro) registry.

The latest `salmon` is available at https://hub.docker.com/r/combinelab/salmon, but alevin-fry seems to only be available as part of https://hub.docker.com/r/combinelab/usefulaf, which is probably fine except that is is a pretty large image.

**Comment by jashapiro** [comment]
closed by #220
