### ISSUE TITLE
Make metadata.json file pretty

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#222]
When I was reviewing #220 and I was looking at the outputs I was reminded again about our `metadata.json` file being ugly and I think it would be nice to make them pretty like the other `json` files that are now being written to the checkpoints folder. This should be an easy fix because I think we just need to add the `pretty=TRUE` option to `jsonlite::write_json` when we are writing out that file.

**Comment by jashapiro** [comment]
closed by #223
