### ISSUE TITLE
Include intron counts as part of SCE objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#229]
As discussed in #214, we are planning to include both the matrix with intron reads counted and the original counts matrix (that does not include intron reads) as part of the returned SCE objects. This means that the current matrix that is found in the `counts` slot will need to be moved to a new assay inside the SCE object and then the new `counts` assay will contain the updated counts matrix containing introns. 

After addressing https://github.com/AlexsLemonade/scpcaTools/issues/136 and modifying `read_alevin_mtx` to use `fishpond`, we will then be able to output both types of matrices and create the SCE object. This change may result in changes to the arguments in `read_alevin`, which will need to be propagated to [`generate_unfiltered_sce.R`](https://github.com/AlexsLemonade/scpca-nf/blob/main/bin/generate_unfiltered_sce.R). This issue is to track any changes that may need to take place in `scpca-nf` after the adjustments to `scpcaTools` to create SCE objects with the intron counts.

**Comment by jashapiro** [comment]
Closed by #242 ?
