### ISSUE TITLE
Create a script for integrating SCE objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#247]
Before we can add a process to the integration workflow started in #240 for integration with `harmony` and integration with `fastMNN`, we will probably want to have a script that can be used for integration that is run by each of those processes. 

One option is to have a script for each process, so one script that will integrate using `harmony` and then another separate script to integrate using `fastMNN`. However, I think a lot of steps might be repeated and we might be able to combine into one script with an integration method as the input. Provided with an integration method, the script would perform either `harmony` or `fastMNN` and then output the integrated object. 

Another alternative is to allow for multiple integration methods as the input and then perform integration for both methods with the same process in the workflow. But I think we want to keep these processes separate as it would be easier to remove one process or not perform one type of integration in the future. Either way, we could create one script that can perform both integration methods and takes as input a merged SCE object and an integration method to perform and use that same script in two processes.

**Comment by sjspielman** [comment]
> we will probably want to have a script that can be used for integration that is run by each of those processes

To clarify this would be an R script that gets called by a process that will be written to live in an `nf` script, yes?

**Comment by sjspielman** [comment]
> we will probably want to have a script that can be used for integration that is run by each of those processes

@allyhawkins To clarify this would be an R script that gets called by a process that will be written to live in an `nf` script, yes? Somehow in my head I originally thought this was `nf` but reading the issue again I don't think that original thought makes sense!

**Comment by allyhawkins** [comment]
> @allyhawkins To clarify this would be an R script that gets called by a process that will be written to live in an nf script, yes? Somehow in my head I originally thought this was nf but reading the issue again I don't think that original thought makes sense!

Yes that's correct. It would be a Rscript that lives in the `bin` folder and then within a nextflow process that script will get run.

**Comment by allyhawkins** [comment]
Closed by #274
