### ISSUE TITLE
Investigate post-process filtering

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#250]
When looking at some preliminary results, there was a bit of an odd result with SCPCL000533 where the results from miQC don't seem to match the filtering that we actually want to apply. All of the filtering happens in the `post_process_sce.R`, so we should be able to fix this without going upstream to scpcaTools.

For reference, the miQC plot looks like this:
![download](https://user-images.githubusercontent.com/20483/204652040-af832814-3db6-4e09-9bc0-645a9c483402.png)

Which would seem to imply that a large number of cells should be kept. However, only 259 cells are kept and the keep/discard plot ends up looking like this:
![download-1](https://user-images.githubusercontent.com/20483/204652019-de757ba4-2c01-4673-8b14-5ed540401e48.png)

We shoudl investigate what is happening here before cutting another release!

**Comment by allyhawkins** [comment]
Closed by #252
