### ISSUE TITLE
[BUG] Post-processing fails at dimensionality reduction if number of cells post filtering is less than 15

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#260]
**Describe the bug**

When running a project through, there was a failure in the post processing step at the step where we calculate UMAP immediately before writing the `processed.rds` file out. In testing this locally with this library I ran into the failure when calculating UMAP because the number of cells left in the library (6) is less than the number of nearest neighbors that are used as a default for UMAP (15). This library was particularly low and only had 23 cells after empty drops filtering and then was left with 6 post filtering with cutoffs. Unsurprisingly, this library also failed miQC and clustering prior to normalization. 

Here's a copy of the screenshot from tower with the error. 

<img width="639" alt="Screen Shot 2022-12-15 at 3 59 45 PM" src="https://user-images.githubusercontent.com/54039191/207976081-b083b62d-2e8b-4732-89be-0a1827433098.png">

**Version information**
What version of `scpca-nf` are you using, and what version of Nextflow?

`scpca-nf` v0.4.0, nextflow 21.04.1

**Proposed Solution**

Unfortunately we use the UMAPs in the QC report as well, so we will have to make a fix in the post processing script and also incorporate a way to handle missing UMAP results in the QC report. I'm not totally sure how I want to handle this. But I think one approach would be to wrap a `try` around the `runUMAP` and if it fails add a note to the metadata that the UMAP was unable to be calculated (probably just a true/false). We then would need to check the metadata in the QC report to skip out creating the UMAP plots if no UMAP was calculated.

**Comment by jashapiro** [comment]
> Unfortunately we use the UMAPs in the QC report as well, so we will have to make a fix in the post processing script and also incorporate a way to handle missing UMAP results in the QC report. I'm not totally sure how I want to handle this. But I think one approach would be to wrap a `try` around the `runUMAP` and if it fails add a note to the metadata that the UMAP was unable to be calculated (probably just a true/false). We then would need to check the metadata in the QC report to skip out creating the UMAP plots if no UMAP was calculated.

I think this is generally the correct approach. I was thinking at first that we might need to add another parameter to the notebook, but we can check whether a UMAP exists in the `proccessed_sce` object and proceed based on that whether to plot or post a warning. If we pull the UMAP plots into a separate module, we can handle the main logic in the same way we do with CITE-seq etc.: including that module only if UMAP object exists.

We will probably also want to have a big warning at the top of the QC report if there are fewer than X cells (50?) in the processed data set, or maybe a couple thresholds, so we can report on both the filtered and processed cell counts. Maybe different thresholds of warnings if we really want to be ambitious.

**Comment by allyhawkins** [comment]
Closed by #261
