### ISSUE TITLE
Outline cell type section to QC report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#276]
After we have performed cell type classification, we will want to have a way to visualize the cell type assignments. We already have a QC report that is created for each library through the main `scpca-nf` report. We should add a section to this report that includes plots to show the results of cell type assignment. To start we can show a UMAP with the cell type labels. 

Unlike with previous reports, we will want this addition to live in `scpca-nf` so we will have to think about how to append it to the report that is already getting rendered in the workflow that is stored in `scpcaTools`.

**Comment by jashapiro** [comment]
> Unlike with previous reports, we will want this addition to live in `scpca-nf` so we will have to think about how to append it to the report that is already getting rendered in the workflow that is stored in `scpcaTools`.

I think the way we will want to do this is to complete https://github.com/AlexsLemonade/scpcaTools/issues/162, then copy the full template report that is currently embedded in `scpcaTools` into this repo and use that as the input template here (with the addition of cell typing reports.

**Comment by allyhawkins** [comment]
Some things we discussed that should be in the cell type section of the QC report:

- UMAP with cell type labels 
- Heatmap or some sort of plot showing how confident the assignments are
- Summary table of how many of each cell type are assigned
- There was also some future discussion of looking at the ontology labels and comparing assignments across references, but we should start with the first three and then go from there

**Comment by allyhawkins** [comment]
I think we should use this issue to outline some ideas of what we would like to see in the report. Next sprint I will plan to post a diagram of my thoughts for the QC report and then get other people's opinions before we begin development.

**Comment by allyhawkins** [comment]
Here I'm proposing an initial outline for the added cell type section of the QC report. A few things to note: 

- In creating this, I considered how we would display both cell type annotation results, clustering results using a single parameter, aneuploid status, and submitter annotations, if present. The focus is definitely on the cell type annotations and less on clustering and aneuploid status. There is another question that we are not yet addressing regarding which clustering method is best. We previously talked about utilizing tools such as [MultiK](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02445-5), but for now, we are focusing on a single clustering approach to compare cluster assignments with cell-type annotations. If we want to explore other clustering methods in the future, I think we could easily expand this. 
- I know there are a lot of UMAPs, but I think it's important to show them with the various annotations. I put them in a 4X4 block plus an extra for the submitter annotations if present, but I think we might want to make them separate plots printed right after the other. I'm worried about the 4x4 being too crowded, depending on how many annotations or clusters there are for a given sample.
- We discussed having a single combined visual that shows both cell type annotations, clusters, and CNV status. I think the ideal solution here would be to have both cell type annotations from SingleR and CellAssign represented with ontology IDs, and then it would be easier to combine them in a single plot. Also, having ontology IDs would allow us to calculate the percentage of cells with the same assignment with both methods. However, I don't know if we want to spend time converting all the cell types in PanglaoDB to their ontology terms. So the solution I came up with is a heatmap broken up by cell type method (y-axis) with cluster assignments on the x-axis. The heatmap would be colored by the number of cells that are overlapping. I also included an annotation bar for the cell type annotations and cluster assignments to show how many cells in each cell type/cluster are aneuploid. What do we think of something like this? I am very open to other ideas if people have them! 
- I also created a similar heatmap for looking at each of the cell type references directly to the submitter annotations. This section would only be present if submitter annotations existed. Additionally, instead of only looking at % aneuploid cells for each cell type, we could add an annotation bar that shows if cell types are tumor/ normal based on the submitter type. We may want something that directly compares the number of cells that are tumor/normal according to submitters vs. aneuploid with CNV. I didn't include that yet because we are still exploring CNV inference, and I think that's a later thing to add. 
- The last section is looking at the distribution of scores for SingleR and prediction scores for CellAssign. This would be using the delta median method we had used previously, where we subtract the top score from the median score. The scores have different ranges of values, so we will need to separate plots for each method. Another caveat is that we haven't made this plot yet for CellAssign, so it could be useless. 
- With the plots made here, I plan to develop them with/ without submitter ids and with/without CNV status. Those are both things that can be incorporated once the base of the report has been started. 
- Sorry about all the colors, the actual colors I picked are mostly meaningless, and I don't plan on using those color schemes. I just had a bit of fun while drawing this. 

Please look at the attached outline and provide any feedback you may have by EOD Tuesday, August 22. Tagging @jashapiro @sjspielman @jaclyn-taroni. 

[Cell type report Aug 16, 2023.pdf](https://github.com/AlexsLemonade/scpca-nf/files/12362961/Cell.type.report.Aug.16.2023.pdf)

**Comment by sjspielman** [comment]
Responding here with some initial thoughts!

- I agree with your choice to not spend much time on clusters themselves. As you said, this report is not primarily about clustering, and a clustering-specific report (e.g. in `scpca-downstream-analyses`) would need a lot more exploration that will really bog down this report and detract from the central message of cell types.
	- We should add a statement explaining how clusters were created, and _perhaps_ indicate that they can further explore clustering methods & parameter space on their own.
- I'm worried about emphasizing CNV status given some of the _preliminary results_ in https://github.com/AlexsLemonade/sc-data-integration/pull/230. It would be ideal to be able to emphasize it, but I'm skeptical that we will find a way to have confidence in it! Following more discussion & exploration of how to get reliable estimates here, we'll have to wait and see how this pans out. So, good call to mock this up with and without CNV status!
- UMAPs - Yeah...we do need four (plus option for 5th if we have submitter info), but I do agree it might get very busy especially since we can't really have a shared legend (we _could_ for the SingleR + CellAssign panels with some ontology IDs, but as you said that's a real time investment!).
	- In a 2x2 grid, we'd probably want to have SingleR and CellAssign on the same line, so clockwise from top left I'd order: clusters, CNV, SingleR, CellAssign
	- That said, I imagine we'll want to play around with layout here to make it less busy - we may even want to not have a grid and just four "stacked" UMAPs, if the legends take up a lot of space.
- Heatmaps - no notes, I think what you've sketched is a good place to start, and we'll see how it looks!
- Score plots - If a delta median approach does not work well for CellAssign, we probably want these plots on different lines, separated by explanations of what each score is. We should only put these plots on the same line if the score calculation is the same for both.
	- I do tend to think we should place this closer to UMAPs, as you asked in the sketch. I think it would be good to emphasize some measures of confidence before showing the heatmaps - otherwise we're almost "hiding" the confidence, which IMO needs to be more front-and-center. We don't want to convey meaningful comparisons if the results themselves aren't reliable.

**Comment by jashapiro** [comment]
> UMAPs - Yeah...we do need four (plus option for 5th if we have submitter info), but I do agree it might get very busy especially since we can't really have a shared legend (we _could_ for the SingleR + CellAssign panels with some ontology IDs, but as you said that's a real time investment!).
> * In a 2x2 grid, we'd probably want to have SingleR and CellAssign on the same line, so clockwise from top left I'd order: clusters, CNV, SingleR, CellAssign
> * That said, I imagine we'll want to play around with layout here to make it less busy - we may even want to not have a grid and just four "stacked" UMAPs, if the legends take up a lot of space.

Just responding to this one point with what is probably a bad idea: maybe we want to use tabs for these?
https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

**Comment by allyhawkins** [comment]
Thanks so much for your notes! All great points!

I think in terms of layout, I definitely resonate with this point: 
> I do tend to think we should place this closer to UMAPs, as you asked in the sketch. I think it would be good to emphasize some measures of confidence before showing the heatmaps - otherwise we're almost "hiding" the confidence, which IMO needs to be more front-and-center. We don't want to convey meaningful comparisons if the results themselves aren't reliable.

> Just responding to this one point with what is probably a bad idea: maybe we want to use tabs for these?
https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

I kind of like this idea actually... I'd want to see it actually implemented but I think it may be a good way to show the UMAPs without over crowding things. But otherwise, yes I was thinking 4 stacked UMAPs if the grid looks bad.

> I'm worried about emphasizing CNV status given some of the preliminary results in https://github.com/AlexsLemonade/sc-data-integration/pull/230. It would be ideal to be able to emphasize it, but I'm skeptical that we will find a way to have confidence in it! Following more discussion & exploration of how to get reliable estimates here, we'll have to wait and see how this pans out. So, good call to mock this up with and without CNV status!

I definitely agree that CNV status is iffy at this point. I think if there's a way we can display confidence in the CNV calls as we are in the cell type annotations than that might be a good compromise. To be honest, the cell types won't always be accurate either. My take is that the goal of this report is to show what happens when we use these automated methods and then also show some statistic to help users decide how much they trust this information.

**Comment by sjspielman** [comment]
> I think if there's a way we can display confidence in the CNV calls as we are in the cell type annotations than that might be a good compromise.

Was just going to start to look into this now!

**Comment by jaclyn-taroni** [comment]
I have little to add over and above the points raised so far. My "spidey senses" were tingling when I arrived at the delta median plot for CellAssign, but I think that's pretty well-covered by @sjspielman's points here: 

> * Score plots - If a delta median approach does not work well for CellAssign, we probably want these plots on different lines, separated by explanations of what each score is. We should only put these plots on the same line if the score calculation is the same for both.
> 
>   * I do tend to think we should place this closer to UMAPs, as you asked in the sketch. I think it would be good to emphasize some measures of confidence before showing the heatmaps - otherwise we're almost "hiding" the confidence, which IMO needs to be more front-and-center. We don't want to convey meaningful comparisons if the results themselves aren't reliable.

**Comment by allyhawkins** [comment]
The contents of the report have all been filed into separate issues. I'm going to go ahead and close this, but if you have additional comments about any of the plots, feel free to reference the new issues.
