### ISSUE TITLE
Inventory CITE-Seq data for controls

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#292]
For ScPCA projects with CITE-Seq data, we should look around the data to see if there might be any (probably negative if anything) controls ADTs in there that could be considered during filtering and normalization. As of now, the projects with CITE-Seq are `SCPCP000003` and `SCPCP000007`.

**Comment by sjspielman** [comment]
All antibodies in the given SCPCA projects are named as either `CDXXX` or `HLAXXX` - this implies they are all human genes, since human TotalSeq kits (which we can't assume were used, but it's not unlikely they were used!) include `Isotype` (or `Iso`) prefixes for negative controls (generally mice).

I've also looked at a couple SCEs for each project, and there are no "suspiciously low" `rowSums(counts())`, which means either a negative control is unlikely or there is a wild amount of contamination (which itself is probably 🤞 unlikely!).

So, it's unlikely that our current data holds negative control ADTs, and in the absence of definitive information, we're not going to assume any. In the future we may want to add support for _known_ negative controls. 
Either way, if this assumption that we have no negative controls is wrong, we also provide raw counts data to users to process how they choose.

**Comment by allyhawkins** [comment]
Did you check the teachey/tan data? Looking at the list of ADT's in the barcode file there's a bunch of `Isotype` tags?

**Comment by sjspielman** [comment]
Hm, @allyhawkins I hadn't looked there because that project shows has `has_CITE=FALSE` in our admin project metadata but will check it out. Does this imply we need to update our project metdata though?

**Comment by sjspielman** [comment]
Closing this in favor of other issues over in admin.
