### ISSUE TITLE
Include metadata indicating CITE-seq negative control ADTs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#298]
Related to #293 
One aspect of cite-seq processing will involve knowing whether there are negative control ADTs to filter on (i.e., remove cells with non-0 counts). This information will need to be included in metadata file, along with the other CITE-seq specific columns (`feature_barcode_file` and `feature_barcode_geom`). 

How to tackle this?
- Name the column something like `feature_negative_controls`
- This column can be filled in with a single value, or  `semicolon;separated;ADTs`, if >1. 
- (?) Perhaps we make this column optional; if the column is missing, we assume no negative controls.

**Comment by jashapiro** [comment]
I would suggest we _not_ put this in the metadata file, but rather encode it in the barcode files themselves. I am not 100% sure if we can add an extra column to the tsv file that lists the ADT sequences and have salmon index it as normal, but if not, that is a simple `cut` command away.

**Comment by sjspielman** [comment]
Effectively closed by https://github.com/AlexsLemonade/ScPCA-admin/pull/525.
