### ISSUE TITLE
Multiple alternative experiments

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#311]
This issue is primarily intended for discussion as we move towards adding CITEseq processing (filtering/normalization) into the workflow. While working towards this goal, I noticed some aspects of the pipeline which may have been written with a longer term goal of accommodating multiple alternative experiments, although offline discussion has suggested this is a feature (⚠️ pun alert) that we don't implement.

I'm specifically looking at these places:

- In the `make_merged_unfiltered_sce` process, we assign a name for the alternative experiment based on the technology metadata. This choice on its own does not mean that we are setting up for multiple experiments, but it _could_ suggest that the altExp name should be sent into to later processes so that the right altExp can be pulled out to work with (for example, to be filtered on!).
https://github.com/AlexsLemonade/scpca-nf/blob/a6b87e474888cdfc4f11c137b5ab138b730c97ae/modules/sce-processing.nf#L30-L59
 
- In the post process Rscript itself `post_process_sce.R`, we have this for-loop that implies the potential existence of multiple named altExps. 
https://github.com/AlexsLemonade/scpca-nf/blob/a6b87e474888cdfc4f11c137b5ab138b730c97ae/bin/post_process_sce.R#L97-L105

To me, it seems the most immediate decision here is whether we need to be passing altExp _names_ through the pipeline to be able to isolate the CITEseq one for processing, in the event there are multiple altExps. If we always only expect 1 altExp, its name is essentially moot so that metadata isn't needed. Along the way, we could also get rid of that for-loop.

On the other hand, if we think we might in the longer term want to handle multiple altExps, then the metadata name does need to be passed through to save us from our future selves, and we'd keep the for-loop.

Tagging @jashapiro @allyhawkins for discussion!

**Comment by jashapiro** [comment]
The name of the altExp are already passed along as `meta.feature_type` so there is no need for a change there at this time.

Updating the workflows to handle multiple AltExps is something we have not yet had to support, and will require substantial reengineering. The most likely scenario is that we will get data that has something like multiplexing and CITEseq or multiplexing and ATAC, in which case we would be adding a separate process and flow among processes. The merge script would have to change, as would how we designate those files in the `technology` column.

Which is basically to say, this a problem we can face when we actually have data with multiple altExps. I don't think there are any changes that need to be made at this time.

**Comment by sjspielman** [comment]
Thanks @jashapiro! Followup from your comment, I am maybe understanding something I hadn't before. Does this wrangling add `feature_type` to the metadata _forever_? I had thought it was maybe just scoped locally to change metadata within this process, but if this change to `meta` is "global", then :tada:!
https://github.com/AlexsLemonade/scpca-nf/blob/a6b87e474888cdfc4f11c137b5ab138b730c97ae/modules/sce-processing.nf#L42-L44

**Comment by sjspielman** [comment]
This was just an issue for discussion, and it has been discussed! Can be closed.
