### ISSUE TITLE
Add RAD checkpoint for barcode features

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#315]
Because feature mapping is fast, we hadn't bothered with keeping a checkpoint file for those steps. However, for transmitting results without underlying sequence data from external users, it would be nice if we also had checkpoints for the feature data RADs as well.

We probably could keep the `alevin-fry` output matrices instead of the RAD files, as I do not expect much change in the quantification steps for feature barcodes, but either way, we should probably have _some_ checkpoint for these files, modeled after our other checkpoint steps.

**Comment by allyhawkins** [comment]
> We probably could keep the alevin-fry output matrices instead of the RAD files, as I do not expect much change in the quantification steps for feature barcodes, but either way, we should probably have some checkpoint for these files, modeled after our other checkpoint steps.

I think for simplicity in getting submissions from external users we should have them upload the same type of checkpoint files from both RNA and feature data. So either we make the checkpoints output the RAD files or the alevin-fry files. I would argue that we keep things consistent with how we have things for other modules and output the RAD files, although they are bigger. 
I think if we want to go for smaller files and get the matrices instead I think we should change the checkpoint for the RNA module to match, which is a little more work.

**Comment by jashapiro** [comment]
> I think for simplicity in getting submissions from external users we should have them upload the same type of checkpoint files from both RNA and feature data. So either we make the checkpoints output the RAD files or the alevin-fry files. I would argue that we keep things consistent with how we have things for other modules and output the RAD files, although they are bigger.
> I think if we want to go for smaller files and get the matrices instead I think we should change the checkpoint for the RNA module to match, which is a little more work.

Yeah, I think the consistency is worth something here. I want to keep RAD files for RNA in case of updates to AF, so I think that makes the most sense.

**Comment by allyhawkins** [comment]
Closed by #317
