### ISSUE TITLE
Document stub workflow

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#333]
In https://github.com/AlexsLemonade/scpca-nf/pull/332, I added some test files (all blank) to use when testing with the `-stub` workflow processes, which can save lots of time downloading big files & also adds a way to test workflow logic automatically.

This needs some documentation in the internal instructions for development, along with adding the requirement of a `stub:` for each new process we add.

**Comment by allyhawkins** [comment]
Closed by #376
