### ISSUE TITLE
Update QC report based on CITE-seq post-processing

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#336]
Following changes made to incorporate CITE-seq post-processing into the pipeline, we'll need to update QC report.

#### [`qc_report.rmd`](https://github.com/AlexsLemonade/scpca-nf/blob/development/templates/qc_report/qc_report.rmd) 
  - Update relevant phrasing throughout
    - It would be nice to be able to have logic for whether certain text appears, for example here: https://github.com/AlexsLemonade/scpca-nf/blob/6953ae72d0b8600b09bc8d50205260bb611a4e7e/templates/qc_report/qc_report.rmd#L473 
  - The string for `scpca_filter_method` metadata has now changed, so think about that...
  -  Some changes needs to happen to reflect that filtering in the `_processed.rds` object is filtered for _both_ RNA and ADTs.
  - Update the `basic_statistics` table appropriately. Needs an `if` to check for CITE-seq and rows for more stats https://github.com/AlexsLemonade/scpca-nf/blob/6953ae72d0b8600b09bc8d50205260bb611a4e7e/templates/qc_report/qc_report.rmd#L233-L238
  - TBD: Should this plot only show RNA-based filtering? As written, it will include ADT-based filtering as well, which seems reasonable to me if there are ADT counts! Just need to update text (and maybe make the text conditional) https://github.com/AlexsLemonade/scpca-nf/blob/6953ae72d0b8600b09bc8d50205260bb611a4e7e/templates/qc_report/qc_report.rmd#L442-L450

#### [`cite_qc.rmd`](https://github.com/AlexsLemonade/scpca-nf/blob/development/templates/qc_report/cite_qc.rmd) 
  - Also select target type https://github.com/AlexsLemonade/scpca-nf/blob/6953ae72d0b8600b09bc8d50205260bb611a4e7e/templates/qc_report/cite_qc.rmd#L38
    - TBD: We end up creating this column if users didn't provide. Do we want to tweak the implementation to add a metadata indicator if this information was user-provided?

CC @allyhawkins @jashapiro , tagging (_this is a pun_) if you have thoughts on some of the TBD items above, or anything else! This might not be an exhaustive list of changes, but it's enough to get started and more will gel once I start getting going.

**Comment by jashapiro** [comment]
> * TBD: Should this plot only show RNA-based filtering? As written, it will include ADT-based filtering as well, which seems reasonable to me if there are ADT counts! Just need to update text (and maybe make the text conditional)

I think it is fine to show all of the filtering that was applied: I will note though that I think we can just use the values in `filtered_sce` rather than checking whether they are present from `processed_sce`? We do put those labels in both SCE files, correct?



> * TBD: We end up creating this column if users didn't provide. Do we want to tweak the implementation to add a metadata indicator if this information was user-provided?

I assume you mean the target column here: adding an indicator is fine, but I'm not sure it is needed: the reason to include this info is to indicate how it was used, which I think the column alone does cover.

**Comment by sjspielman** [comment]
> I think it is fine to show all of the filtering that was applied: I will note though that I think we can just use the values in `filtered_sce` rather than checking whether they are present from `processed_sce`? We do put those labels in both SCE files, correct?

:100:, will clean this up!

**Comment by sjspielman** [comment]
Closed with #343
