### ISSUE TITLE
Idea: Include R package versions in QC report

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#337]
In the QC report, we include relevant pre-processing software versions: 
https://github.com/AlexsLemonade/scpca-nf/blob/6953ae72d0b8600b09bc8d50205260bb611a4e7e/templates/qc_report/qc_report.rmd#L192-L204

But, I don't see an equivalent table for our "core" R packages...
- `SingleCellExperiment`
- `scran`/`scater`/`scuttle`
- `miQC`
- `DropletUtils`
- `scpcaTools`
- maybe `tidyverse`? one could argue this either way...

Not all of these packages appear in the `sessionInfo()`, so it might be worth adding a quick table to the QC report that contains this information.

**Comment by jashapiro** [comment]
I might argue that the reference to a specific workflow release is sufficient for this purpose. It is entirely possible that different versions of packages and tools will be used in different processes, depending on the docker images in use, so creating a comprehensive listing here may not be straightforward or easily maintained.

**Comment by sjspielman** [comment]
> It is entirely possible that different versions of packages and tools will be used in different processes, depending on the docker images in use,

Ah, this is a good point that I hadn't appreciated! Makes sense.

**Comment by sjspielman** [comment]
Closing this due to container differences, will be hard to pin down!
