### ISSUE TITLE
Rename CITEseq to adt

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#347]
From this discussion: 
https://github.com/AlexsLemonade/scpca-nf/pull/345#discussion_r1213703305

Currently, we name the alternative experiment with ADT counts, if present, `CITEseq` as default. But really the whole SCE object is CITEseq (RNA+ADT), so we should make the altExp name more specific to what it actually contains - `adt`.

This will involve changing some R code to rename the default `CITEseq` name to `adt` in `filter_sce_rds.R` and `post_process_sce.R`, but not the `technology` field in the TSV metadata whose name will still be `CITEseq`. Though, the `feature_type` which gets pulled out could be renamed to `adt` for overall consistency, even though this isn't something users will see.

Either way I need to look into what's happening here - https://github.com/AlexsLemonade/scpca-nf/blob/bb3215a765e4649815388dba9609379189c97c89/bin/generate_unfiltered_sce.R#L116-L118

**Edit** - if `feature_type` is updated, no need for `if` statement ^ which seems cleaner to me, so that's where I'm headed!

**Comment by sjspielman** [comment]
Additional thoughts...

- QC fields `altexps_CITEseq_<stat>` will get updated to `altexps_adt_<stat>` automagically as long as the altExp is named `adt`
- What do we think about the metadata field that gets returned to users `has_citeseq`? Should we move to `has_adt`? CC @jashapiro @allyhawkins

**Comment by allyhawkins** [comment]
> What do we think about the metadata TSV column that gets returned to users - has_citeseq? Should we move to has_adt? CC @jashapiro @allyhawkins

Do you mean `SCPCLX_metadata.json`? I don't know if we need to change that because we also refer to it as CITE-seq in the user facing docs. We also have icons on the portal for including CITE-seq. I think it's okay to leave it there right now when we are referring to if there is CITE-seq data present.

**Comment by sjspielman** [comment]
Noting that these changes are partly done, partly incoming in #343. We can close out when #343 is all set.

**Comment by sjspielman** [comment]
Noting that #357 also found a spot where we missed this renaming!

**Comment by sjspielman** [comment]
#343 and #357 are now all set, so this can be closed.
