### ISSUE TITLE
Accommodate bulk fastq files without `R1` in the file name

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#352]
In running the bulk data from SCPCP000003, I ran into an issue because the file names don't contain R1 or R2. We are trying to run single-end bulk data where the filenames only contain the `submitter_id.fastq.gz`. However, for the bulk workflow right now we only grab fastq files that match the pattern of `*_R1_*.fastq.gz`. This means the input files are empty when trying to run this data. 

With single-end bulk RNA-seq, we may encounter files that do not contain `R1` in the filename, so we should accommodate for that. The difficulty here is that we will need to still be able to separate out R1 and R2 for paired end sequencing. 

I think we should break out single and and paired end into two separate channels. In the single-end channel we will grab all of the files that are fastq files, regardless of R1 or R2 in the name. The paired-end channel will be the same as we have it now, specifically pulling out R1 and R2 files separately. Then both channels will be run through the `fastp` process to produce the trimmed reads. The output can be mixed together before proceeding to running `salmon`.

**Comment by jashapiro** [comment]
I wonder if we can use glob negation for R1 files:

Something like:
`"!(*_R2_*).fastq.gz"`

**Comment by jashapiro** [comment]
To expand a bit: R1  or untagged fastq files should be caught would be caught by `"!(*_R2*).fastq.gz"` and R2 files would still be caught by `"*_R2*.fastq.gz"`. But I just realized this won't work in the case that there are `I1` files in the directories, which we definitely have.

I actually think I might favor adding `_R1_` to the file names in cases like this, rather than making the workflow more complex

**Comment by allyhawkins** [comment]
> I actually think I might favor adding _R1_ to the file names in cases like this, rather than making the workflow more complex

I'm fine with this if that's what we want to do. The only thing it means is that if we get additional bulk files that have no R1 like these, then we will have to do the same thing and remember to rename them.

**Comment by jashapiro** [comment]
> > I actually think I might favor adding _R1_ to the file names in cases like this, rather than making the workflow more complex
> 
> I'm fine with this if that's what we want to do. The only thing it means is that if we get additional bulk files that have no R1 like these, then we will have to do the same thing and remember to rename them.

Agreed... it's a bit messy, but since we do enforce filenames otherwise, I think we should be okay. We will also need to make sure to update the md5 files to match.

**Comment by allyhawkins** [comment]
> Agreed... it's a bit messy, but since we do enforce filenames otherwise, I think we should be okay. We will also need to make sure to update the md5 files to match.

Okay, I'm going to close this and file another issue in `ScPCA-admin` to track changing the filenames and md5s.
