### ISSUE TITLE
Ensure output metadata is complete

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#358]
While working on CITE-seq post-processing, I wondered if we want to expand the output metadata with more ADT info.

https://github.com/AlexsLemonade/scpca-nf/blob/19722f43c8b5dd8ebacd0b3202ebee0b0a18ce90/bin/sce_qc_report.R#L163-L207

Specifically:
- I see we have _normalization_ information in there, but not scpca filter. Should `scpca_filter_method` be added? 
  - Similarly, adt filtering (if citeseq)?
- Since we have normalization for RNA, perhaps it's worth mentioning normalization for adt if citeseq (https://github.com/AlexsLemonade/scpca-nf/pull/343#discussion_r1245384759)

@allyhawkins @jashapiro

**Comment by jashapiro** [comment]
I think that would all be appropriate to add. I don't think we expose everything in those outputs on the front end, but having extra things in the json should not cause any trouble.

**Comment by sjspielman** [comment]
> It is not part of the download directly, but it is compiled into a table for the download, which we could expand.

From what I see, the values are not all exposed in the portal, but they _are_ all in the TSV download. For example for `SCPCS000018` (chosen b/c it is small!) - 
[single_cell_metadata.tsv.txt](https://github.com/AlexsLemonade/scpca-nf/files/11897418/single_cell_metadata.tsv.txt)

**Comment by sjspielman** [comment]
> I see we have normalization information in there, but not scpca filter.

I did not read this carefully enough! We _do_ have `scpca_filter_method`, but it's called `cell_filtering_method`. Therefore...

- This should probably be renamed `rna_filtering_method`. But, I'm wary of making that kind of a change (in part because of pending cite-seq-only portal updates..)
- We can still have an `adt_filtering_method` in there even though that one isn't called rna!

**Comment by jashapiro** [comment]
> > I see we have normalization information in there, but not scpca filter.
> 
> I did not read this carefully enough! We _do_ have `scpca_filter_method`, but it's called `cell_filtering_method`. Therefore...
> 
> * This should probably be renamed `rna_filtering_method`. But, I'm wary of making that kind of a change (in part because of pending cite-seq-only portal updates..)
> * We can still have an `adt_filtering_method` in there even though that one isn't called rna!

I think this is fine, since the fell filtering we actually _do_ is based on the RNA, so the name still fits.
