### ISSUE TITLE
Add row level metadata to AnnData objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#368]
To make our AnnData output as compliable as possible with CZI, we need to update the existing row/gene metadata present in the AnnData objects to include the necessary entries.
The full documentation can be found here: https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#var-and-rawvar-gene-metadata

In brief we will need to add:

- make sure the index contains Ensembl gene identifiers (I'm pretty sure this is already the case) 
- indication of if features are filtered between raw and normalized 
- Feature biotype ("gene")
- Feature name 
- Feature reference 

Again, we might want to consider if we should include these in the SCE objects prior to converting to AnnData so they are automatically there.

**Comment by sjspielman** [comment]
Closed by #428
