### ISSUE TITLE
Account for different file name structures when running Salmon

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#392]
We had a user attempting to run the workflow and was running into errors that the input fastq files weren't found. This was because their file names had `_R1.fastq.gz` rather than `*_R1_*.fastq.gz`. We also had this issue with one of the bulk projects. I think we should do one of two things: 

1. Document that the file names should contain the `_R1_` pattern so that users know if they need to change their filenames. 
2. Change the workflow to be more flexible in finding files. Personally, I like this option because I think changing a bunch of filenames for a user could be a pain.

**Comment by jashapiro** [comment]
I agree... ending with `_R1.fastq.gz` seems reasonable enough, so we should support that. I don't think we want to be too flexible (I would prefer to keep `R1` as required, even for single-end sequencing), but we should be able to accommodate  ending with `R1` with a glob like: 
`*_{R1,R1_*}.fastq.gz`

**Comment by allyhawkins** [comment]
Closed by #397
