### ISSUE TITLE
Update get_refs.py to include cell typing references

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#399]
Following on https://github.com/AlexsLemonade/scpca-nf/pull/398, and when cell typing is actually incorporated into the workflow, we will need to make sure those get downloaded for users who might need to run without access to the internet.

There are at least two thoughts I have about this that may turn this into a slightly larger issue or force some reconsideration of how we handled training references, and might argue again for a json file with the references in it.

The first is that in the `reference_paths.config` file we use two levels of `params` references, which I had previously avoided to allow easier parsing of the file within `get_refs.py`. Specifically, we use `params.celltype_ref_dir`, which saves some typing but means we would have to parse that specifically when getting references: https://github.com/AlexsLemonade/scpca-nf/blob/bd905535bb6e2dd81ae2f1861ae799e9d26607c7/config/reference_paths.config#L9C1-L16C72

The solution I would propose there is to remove that variable and simply define all of the subpaths with reference to `params.ref_dir`, e.g.:

```
// output from save_singler_refs() process
singler_references_dir = "${params.ref_dir}/celltype/singler_references"
```

However, this raises another question/problem, which is that `singler_references` is a directory, and the download script can not list directories (for AWS security reasons, a logged in user can't run `ls` on a prefix, or at least we don't have that set up). So we need to define every file either in the `get_refs.py` script or in a json file (or other reference file) that the script can read. Since these files are likely to change more often, I favor the json option. This leads me to think that the workflow that creates the cell typing references maybe should also output a json file of the paths to the references that it uses/creates? If that is done, then `get_refs.py` can discover them more easily.

One thought is that this json file could live at `${params.ref_dir}/celltype/celltype_refs.json`, which would allow it to be updated outside of the workflow itself, though I might be less enamored with that overall.

**Comment by allyhawkins** [comment]
Can we close this in favor of #560

**Comment by jashapiro** [comment]
Hah, yes!
