### ISSUE TITLE
Account for sample metadata in integration workflow

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#403]
"addition" is the wrong word, but yes, accounting for the new metadata in the integration workflow. But I see that is mostly a function in `scpcaTools`, so we will need to account for it there. Which makes me wonder if the code for adding sample data table to metadata should be there as well? Probably add both in a single Issue/PR.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/scpca-nf/pull/400#discussion_r1291431558_

We will need to make sure that the sample metadata present in the individual SCE objects makes it to the `colData` of the merged SCE objects.

**Comment by jashapiro** [comment]
Do we need to add to the `colData` or should we keep it as a separate table/variable in the `metadata` slot? I was thinking the latter. 

So the idea would be we would 
1. Make a `add_sample_metadata()` function that would add a `sample_metadata` data frame to `metadata(sce)`
2. `merge_sce_list()` would account for the possibility of `metadata(sce)$sample_metadata` tables in the `sce` objects to merge, and combine those in the merged sce metadata.
3. We could also add a function to copy data from the `sample_metadata` to `colData` by sample id, which might be useful.

**Comment by allyhawkins** [comment]
I think for the merged object we would want it in the `colData` because then it would be easier for users to split objects or grab things from the object based on sample level metadata for downstream analysis. Also if doing things like differential expression, you would pull out the `colData` and group by columns present in the data.

**Comment by allyhawkins** [comment]
I'm going to close this as the sample metadata is now merged as part of `scpcaTools`.
