### ISSUE TITLE
Initiate cell type QC report and add summary tables 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#408]
We need to add a cell type specific section to the current QC report. We should create a separate child report that is added if the object contains cell types. This is similar to how we handle the CITE-seq section of the QC report. 

As outlined in #276, the first section will contain summary tables. There should be one summary table per cell type annotation method that was performed. Each table should include two columns, `cell type` and `total cells`. We should also create a table for submitter annotations if they are available.

**Comment by sjspielman** [comment]
Development note - to support preparing the QC report, we want a processed object that contains both clusters and cell types. For this, I am running `SCPCL000001` (which already has clusters) through the cell typing workflow so we can use it for establishing the report.

**Comment by sjspielman** [comment]
Closed by #422
