### ISSUE TITLE
Add plot for SingleR delta median score to the cell type report 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#410]
The third section of the cell type QC report should summarize the metrics reported for cell type annotation. For `SingleR`, we will calculate the delta median score - or the difference between each cell's top and median scores. Then, we want to create a plot that summarizes that information with delta score on the y-axis and cell type on the x-axis. 
See #276 for any additional notes about layout.

**Comment by sjspielman** [comment]
Closed by #432
