### ISSUE TITLE
Include a heatmap comparing cell type annotations to clustering results in cell type report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#412]
The fourth section of the report should include a heatmap that directly compares the cell type annotations with both `SingleR` and `CellAssign` to clustering assignments available in the SCE object. 
The heatmap should look similar to the picture below, but right now, we are not including the aneuploid/ diploid status. 

<img width="646" alt="Screenshot 2023-08-23 at 2 27 44 PM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/b5555a82-0b7f-4e1d-8252-86e5f46eb253">

See #276 for any additional notes about layout.

**Comment by sjspielman** [comment]
Closed by #423
