### ISSUE TITLE
Include a heatmap comparing cell type annotations to submitter annotations in cell type report 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#413]
The last section of the cell type report should be a similar heatmap to #412, but comparing cell type annotations to submitter annotations. This section will only be included if submitter annotations are available. This should look like the picture below, but again, there is no aneuploid/diploid status right now. 

<img width="608" alt="Screenshot 2023-08-23 at 2 29 08 PM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/726ca4c5-0a4d-42a0-91b8-6cb3674f2ad3">

See #276 for any additional notes about layout.

**Comment by sjspielman** [comment]
Zenhub has been forsaking me all day despite many reloads and cache clears, so for now, I'll just comment that this should be **BLOCKED BY #407.**

**Comment by sjspielman** [comment]
Closed with #457
