### ISSUE TITLE
Add cell type workflow into main workflow

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#415]
Right now we have a separate workflow specifically for cell typing. We will need to add the workflow into the main workflow.

**Comment by allyhawkins** [comment]
Just noting that when we do add the cell typing into the main workflow, we should include a parameter for whether or not cell typing should be performed. By default we don't want to do cell typing on every sample that's run through the workflow.

**Comment by sjspielman** [comment]
Question for discussion: What's our preferred approach for passing in _cell type metadata_? We've been using a [project-specific file](https://github.com/AlexsLemonade/ScPCA-admin/blob/a13a93fb7cdacd64f8162affc45994265ff00c90/sample_info/celltype_annotation/scpca-project-celltype-metadata.tsv), but as we don't _require_ a project id to be provided to the overall workflow, I think it would make sense to do one of the following:

- Modify `scpca-library-metadata.tsv` to have expected cell type columns. This way everything just kind of works, but we'd have to have more (optional!) columns. 
- Retain a separate metadata file for cell typing, but also toss library ids and/or run ids into that file, so file would have more rows.

We could also do something fancier and map up which run ids are associated with the project ids in the cell type file, but I do think it's worth it to be more explicit

**Comment by allyhawkins** [comment]
You shouldn't have to do either. I had previously had it in the workflow and all we need to do is tell the main workflow to run the `add_celltypes.nf` workflow. In `add_celltypes.nf` we add in all the library/ project/sample info that we need and filter to the relevant samples based on what's provided. 

I also would still keep `add_celltypes.nf` so we can run it independently like it is. 

This is what I had in there before:
https://github.com/AlexsLemonade/scpca-nf/commit/da47bd7d34f1437470466fbad804afecb7061669

**Comment by sjspielman** [comment]
> This is what I had in there before:

I had forgotten it was once there..! Thanks for the reminder

**Comment by jashapiro** [comment]
Link to fig jam: https://www.figma.com/file/9zH1gXlz9ZlxVrndN4Wy54/cell-type-workflow?type=whiteboard&node-id=0-1&t=fKgV0qjgpXfOkmFo-0
