### ISSUE TITLE
Add `is_primary_data` to objects before converting to AnnData

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#417]
We need to include an [`is_primary_data` column](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#is_primary_data) in the cell metadata for AnnData objects. None of our objects should be `is_primary_data` so I think we can just set this to false for all objects prior to converting to AnnData.

**Comment by sjspielman** [comment]
Closed by #428
