### ISSUE TITLE
Store counts for processed object in raw.X

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#436]
According to the CZI schema, the raw counts should be saved to the `X` layer, unless normalized data is also included. In the event that normalized data is present the raw counts should be moved to `raw.X` and the normalized data stored in `X`. 

Once we complete #429 and have saved the normalized counts to `X`, we will need to go into the AnnData objects and move the `counts` layer to `raw.X`. Unfortunately we cannot do this while converting, so we will need a separate process that reads in the hdf5 file and moves the counts. We probably only want to run this process on the `processed.rds` objects.

**Comment by jashapiro** [comment]
Just thinking this through for a sec... Would we expect to do this processing in R via `reticulate` or by writing two hdf5 files and then a separate `python` script to merge the assays? (or does `zellkonverter` write out both assays? In which case we could probably just leave the default output and move things in python if `logcounts` is present?)

**Comment by allyhawkins** [comment]
`zellkonverter` writes out all assays and stores them to the `layers` slot in `AnnData`. For our objects right now, the `counts` assay is stored as `X` and the other assays are present in `layers`. 

My expectation was to do the following: 
1. For normalized objects, store `logcounts` as `X` when writing out the object. 
2. Have a python script that reads in the processed objects only
3. Move the `counts` from `layers` to `raw.X`
4. Save the modified processed object 

Alternatively, we could write them out so they all look the same and then in a separate process read in only the processed objects and save `logcounts` to `X` and then move `counts` to `raw.X`. 
I was originally trying to save having the secondary process, but now it looks like we will need to do some modifications psot writing the object.

**Comment by allyhawkins** [comment]
Closed by #439
