### ISSUE TITLE
Skip cell typing if results files already exist

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#446]
After we complete #415, we will want to add an option to skip the actual cell type classification for `SingleR` and `CellAssign` if the output already exists. This should save us time whenever we are re-processing samples. Similar to `--repeat_mapping`, except `--repeat_celltyping`. 

In doing this we will want a way to track the reference versions used for both cell typing methods and only skip when both the output files exist and the reference version matches. 
For PanglaoDB references we can pull the date from the file name. For `celldex` reference versions we should match up the package version.

**Comment by allyhawkins** [comment]
Noting that from our discussion this should be done within the `annotate_celltypes` workflow. We will want to add the following checks for each library: 
- if the output tsv from CellAssign exists
- if the reference version matches for CellAssign (date in file)
- if the output tsv from SingleR exists 
- if the reference version matches for SingleR (package version for celldex)

If those conditions are met the process for `classify_SingleR` and `classify_cellassign` will be skipped, but the process for adding cell type annotations into the object will still be run.

**Comment by sjspielman** [comment]
@allyhawkins just wanted to link in this somewhat related issue: https://github.com/AlexsLemonade/scpca-nf/issues/470

**Comment by allyhawkins** [comment]
Closed by #510
