### ISSUE TITLE
Move everything but UMAPs and tables for cell type results to a separate report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#447]
The QC report is a little long with all the cell type information, so we should pull out some of the results from cell typing into a separate report. We want to keep the section and include only the tables and the UMAPs. Then, the rest of the report will get moved to it's own file that gets rendered separately. 

We can render this file within the same script that we use to render the full QC report. We just need to modify the process to include two output html files. 

We will also want to link the full cell type report within the cell type section of the QC report.

**Comment by sjspielman** [comment]
I'm going to actually close this out and it split this up into 2 issues:

- split up the qc report: #481
- update the process to: #482
