### ISSUE TITLE
Standardize how we refer to unknown cell types

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#454]
This was brought up by @allyhawkins in https://github.com/AlexsLemonade/scpca-nf/pull/451#pullrequestreview-1627139453 - 

> [A]nother thought I had is related to how we are labeling "unclassified cells" vs "unknown cells". We should standardize this across methods probably.

Indeed, we should. Here's what we _currently_ have:

### Submitter
- Cells that the submitter did not annotate at all are labeled as `NA`.
- Cells that the submitter attempted to annotate but could not define are labeled as `"Unclassified cell"`

### `SingleR`
- In the pruned labels, cells that could not be confidently annotated are labeled `NA`. 
- In the QC report, we show these in figures/tables as `"Unknown cell type"`.

### `CellAssign`
- Cells that do _not_ have the marker genes are labeled as `"other"`.
- In the QC report, we show these in figures/tables as `"Unknown cell type"`.

**Comment by sjspielman** [comment]
It seems fine to me to leave our terminology here as described in this issue's opening comment. The only thing we might change is change `Unclassified cell` to `Unknown cell type`, but I don't think that is specifically helpful? Indeed, `Unknown cell type` is never actually a label in the SCE; it's just a forward-facing label for the report for singler/cellassign. 

But, if we were to change it, it would be here on `L56`:

https://github.com/AlexsLemonade/scpca-nf/blob/9a47fb05689e9475d3bede44c46ecea496533d2d/bin/add_submitter_annotations.R#L46-L57

---

**OK ALL THAT SAID** I think I may have caught a bug but can't quite tell for sure - can I get some more eyes on this @jashapiro @allyhawkins ?

In the celltype reports, we have this code for formatting cell names:

https://github.com/AlexsLemonade/scpca-nf/blob/9a47fb05689e9475d3bede44c46ecea496533d2d/templates/qc_report/utils/celltype_functions.rmd#L63-L88

Here, any `NA` values in the submitter column are getting replaced with the string `Unclassified cell`. This means, in the report, we are calling **both** a) cells that the submitter didn't annotate (these get `NA` values via the join, and b) cells that the submitter annotated as `NA`. I don't think we mean to do this?!

**Comment by jashapiro** [comment]
I think you are correct that we don't mean to do this. According to https://github.com/AlexsLemonade/scpca-nf/issues/454#issue-1897107453 we should be leaving those as NA (or changing to the string `"N/A"` maybe?)

**Comment by allyhawkins** [comment]
Yes, we should catch that. I think to keep things consistent I would use the following: 

- keep cells that are labeled NA by the submitter as NA
- before joining, any cells that are not found in the labels from the submitter get the "Unclassified cell" label 

This keeps things more consistent with how NA's are labeled in SingleR. There aren't really NA's in CellAssign to match.

**Comment by jashapiro** [comment]
Okay, now I'm a bit confused. 

So say we are looking at cells A & B: Cell A is labeled as `NA` by the submitter, and cell B is not there (presumably filtered before annotation).

We want our end result to be Cell A as "Unclassified cell" and Cell B as `NA`, right?

I wonder if we want to exclude B-type cells from heatmaps, or maybe label them as `Submitter excluded` or something like that?

**Comment by allyhawkins** [comment]
> So say we are looking at cells A & B: Cell A is labeled as NA by the submitter, and cell B is not there (presumably filtered before annotation).

Just to clarify - here Cell A is labeled as NA by the submitter, and cell B is not present in the labels provided by the submitter but it is present in our objects. Therefore it was not a cell that got classified/annotated by the submitter. 

> We want our end result to be Cell A as "Unclassified cell" and Cell B as NA, right?

So with that I would have it flipped. Cell A is NA, to be consistent with where we have NA cells in other places that were classified but not assigned. 
Then Cell B becomes "unclassified" which is different from the classified but not assigned (right now denoted by "Unknown cell type"). I do agree though that we should maybe rename those to be "Submitter excluded".

**Comment by sjspielman** [comment]
@allyhawkins @jashapiro 
I have been torn on this and thinking it over! After marinating overnight, here's my fresher thoughts - 

| Submitter label | Our label in the SCE (& anndata) | Our label in the report |
|----------------|----------|--------------|
| `NA`                 | `NA`       | `"Unknown cell type"` |
| (didn't label)    | `"Submitter excluded"` | `"Submitter excluded"`

I think I like this the best because it keeps things consistent -

- Consistent with how we label singler & cellassign
- keeps our labels closer to how submitters actually labeled their data
  - The challenge is we don't know _why_ they would have assigned certain cells `NA` (did they "exclude" them or did they try but fail to annotate the cell?), but since this isn't something we can really know anyways and there is no guarantee of consistency across projects, deferring to the submitters' labels makes the most sense to me.

**Comment by jashapiro** [comment]
I like that overall... My only thought is that in the report, we might leave the `NA` as `"NA"`? My reasoning here is that it is possible that people will using varying `NA` strings: so we could just preserve whatever they provided rather than worrying about it. We could then just use `na = character()` in `readr::read_*()` to do that.

Takes a bit more careful filtering in later use of the SCE, but I don't think that is terrible.

**Comment by sjspielman** [comment]
> My reasoning here is that it is possible that people will using varying `NA` strings: so we could just preserve whatever they provided rather than worrying about it. We could then just use `na = character()` in `readr::read_*()` to do that.

Ok, to make sure I follow - sounds like you are proposing to treat all possible NA things _as strings_ & use `na = character()` when first reading in the submitter TSV? And then propagate whatever that value is through to the report, and update report text about these annotations along the lines of, "submitter annotations are exactly what they provided, and `submitter-excluded` cells are cells they didn't attempt to annotate".

^ I'm on board with this approach!



---

Note to future self, make a note of what end up with in https://github.com/AlexsLemonade/ScPCA-admin/issues/634

**Comment by jashapiro** [comment]
> Ok, to make sure I follow - sounds like you are proposing to treat all possible NA things _as strings_ & use `na = character()` when first reading in the submitter TSV? And then propagate whatever that value is through to the report, and update report text about these annotations along the lines of, "submitter annotations are exactly what they provided, and `submitter-excluded` cells are cells they didn't attempt to annotate".
> 
> ^ I'm on board with this approach!


Yup, that is my thought!

**Comment by allyhawkins** [comment]
This plan also sounds good to me. Just to note that we should update this section of the sce contents in the user facing docs to reflect this (https://github.com/AlexsLemonade/scpca-docs/blob/development/docs/sce_file_contents.md) 
<img width="828" alt="Screenshot 2023-11-09 at 8 35 38 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/26b1c3c3-69fd-422d-866e-5ea26860cf48">

**Comment by jashapiro** [comment]
We could leave the docs as is (mostly) and just leave `NA` in the SCE object. I guess we would still have to explain that there might be both `"NA"` the string and `NA` the value, which mean different things...

**Comment by sjspielman** [comment]
> We could leave the docs as is (mostly)

I think we want to say "cells that the submitter did not annotate are labeled as **submitter-excluded**"

**Comment by sjspielman** [comment]
> I guess we would still have to explain that there might be both "NA" the string and NA the value, which mean different things

Wait, but if we are reading all as character, and then when joining bringing in new cells as **submitter-excluded**, aren't there `NA` logicals (just strings, if any?)?

**Comment by allyhawkins** [comment]
I'm going to vote for just having one version of NA in the actual SCE object, so using `Submitter excluded` in the SCE object. I think having multiple NA's is way too confusing for a user.

**Comment by sjspielman** [comment]
note also to check for blank strings and `<NA>` (excel style) and "nan"

**Comment by sjspielman** [comment]
Closed by #553
