### ISSUE TITLE
Discussion: How to handle converting SCE to AnnData with 1 cell present

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#461]
I recently have run into an error converting any objects that only have 1 cell from SCE to AnnData (which I mean makes sense given its only 1 cell...). I'm attaching the error that I've been getting and noting that I've narrowed it down to a problem with the `zellkonverter` function that is converting from SCE to AnnData. It appears that a list or some other collection type for the column names is needed when creating the AnnData object, rather than a single character vector. This is because in the case of an object with 1 cell the `colnames(sce)` are just a single string rather than a list of strings... 

<img width="778" alt="Screenshot 2023-09-15 at 9 42 26 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/e38f29f2-2af2-4f09-9190-154a7715a55b">

So we need to decide how to handle this situation. 

1. If SCE's don't have at least 2 cells, we don't convert to AnnData. 
2. We could take this one step further, and if we don't have at least 2 cells after filtering, we just don't even create a processed object... I think that might break more things, though so I'm more hesitant to do this. 
3. There is some secret way to make `zellkonverter` treat the `colnames(sce)` as a list regardless of how many cells are there... but I haven't come up with this answer, and I think outside of changing the function or creating our own AnnData object this is hard to do. 

I would like option 1, but I want to run this by others first and see if others have different ideas. 
@jashapiro @jaclyn-taroni @sjspielman

**Comment by sjspielman** [comment]
Some things in this issue seem promising in _general_, but I too wouldn't know how to tell `zellkonverter` about the column names without, as you say, changing the function.. 
https://github.com/rstudio/reticulate/issues/574

I agree option 1 > option 2 since so much could go wrong with option 2. It's also useful to have a QC report telling us the processed SCE has only 1 cell - although disappointing, it's important information!

**Comment by jaclyn-taroni** [comment]
Option 1 seems reasonable.

**Comment by allyhawkins** [comment]
closed by #463
