### ISSUE TITLE
Update example output with cell type annotations

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#469]
Once we have finalized how we are going to add in cell type annotations into the workflow we will want to update the example output to reflect those changes. This should be done before we make a new release with the cell type annotation in the workflow.

**Comment by sjspielman** [comment]
While we're here, also update some of the example language to not make it seem like submitter is mandatory - 

https://github.com/AlexsLemonade/scpca-nf/blob/df98da392c7e9e0f4d67c008dcc4208cee9db4d4/examples/README.md?plain=1#L19-L25

**Comment by allyhawkins** [comment]
I believe we could just remove this all together since it's not required to run the workflow?

**Comment by sjspielman** [comment]
@allyhawkins agree, this should suffice for us - https://github.com/AlexsLemonade/ScPCA-admin/issues/634

**Comment by sjspielman** [comment]
Noting that :point_up: comments about removing submitter things got handled as part of #502

**Comment by sjspielman** [comment]
Looks like we actually still have a `submitter_cell_types_file` column in [`examples/example_run_metadata.tsv`](https://github.com/AlexsLemonade/scpca-nf/blob/cf78909b57f0ff4f22bc9b926e43754e2ad94738/examples/example_run_metadata.tsv). It also looks like we have one, filled with `NA` on the `example_run_metadata.tsv` in S3. 

We'll want to remove these columns altogether - The first one we'll need to do a PR for here, and the second update directly in S3 as part of generating the new example output.

**Comment by sjspielman** [comment]
> the second update directly in S3 as part of generating the new example output.

✅

**Comment by sjspielman** [comment]
Womp. Signing off for tonight, but this is next on deck...!

```
[-        ] process > bulk_quant_rna:fastp                           -
[-        ] process > bulk_quant_rna:salmon                          -
[-        ] process > bulk_quant_rna:merge_bulk_quants               -
[-        ] process > map_quant_rna:alevin_rad                       -
[a9/fbf0b6] process > map_quant_rna:fry_quant_rna (run01-rna)        [100%] 1 of 1 ✔
[17/361a8f] process > generate_sce:make_unfiltered_sce (library01)   [100%] 1 of 1 ✔
[7d/423c9b] process > generate_sce:filter_sce (library01)            [100%] 1 of 1 ✔
[-        ] process > map_quant_feature:index_feature                -
[-        ] process > map_quant_feature:alevin_feature               -
[-        ] process > map_quant_feature:fry_quant_feature            -
[-        ] process > generate_merged_sce:make_merged_unfiltered_sce -
[-        ] process > generate_merged_sce:filter_sce                 -
[-        ] process > cellhash_demux_sce                             -
[-        ] process > genetic_demux_vireo:star_bulk:bulkmap_star     -
[-        ] process > genetic_demux_vireo:star_bulk:index_bam        -
[-        ] process > genetic_demux_vireo:pileup_multibulk:mpileup   -
[-        ] process > genetic_demux_vireo:starsolo_map:starsolo      -
[-        ] process > genetic_demux_vireo:starsolo_map:index_bam     -
[-        ] process > genetic_demux_vireo:cellsnp_vireo:cellsnp      -
[-        ] process > genetic_demux_vireo:cellsnp_vireo:vireo        -
[-        ] process > genetic_demux_sce                              -
[80/90300e] process > post_process_sce (library01)                   [100%] 1 of 1 ✔
[ee/fd5522] process > cluster_sce (library01)                        [100%] 1 of 1 ✔
[-        ] process > annotate_celltypes:classify_singler            -
[-        ] process > annotate_celltypes:classify_cellassign         -
[-        ] process > annotate_celltypes:add_celltypes_to_sce        -
[-        ] process > sce_qc_report                                  -
[-        ] process > sce_to_anndata:export_anndata                  -
[-        ] process > spaceranger_quant:spaceranger                  -
[-        ] process > spaceranger_quant:spaceranger_publish          -
Join mismatch for the following entries: key=library01 values=
```

**Comment by allyhawkins** [comment]
I'm not sure why this is failing, but just a reminder to add `--perform_celltyping` to the command when running.

**Comment by allyhawkins** [comment]
What's the command that you are using to run this out of curiosity?

**Comment by jashapiro** [comment]
If you ran the code in https://github.com/AlexsLemonade/scpca-nf/commit/1c9092b416b9dbb70626b8b4bd2a29c9381f3cce, then I think the problem is that you used the arg `--celltype_project_metafile` instead of `--project_celltype_metafile`

Each of us is doomed to do this at least once.

**Comment by sjspielman** [comment]
> We might want to make another profile called `example` so we don't have to enter so many command line flags?

This is a great idea!

Ran with this, probably wrong param 🤞 but if not, hopefully something something JSON file.

```
op run -- nextflow run AlexsLemonade/scpca-nf -r development \
  -profile ccdl,batch \
  --perfom_celltyping \
  --run_ids run01 \
  --run_metafile s3://scpca-references/example-data/example_run_metadata.tsv \
  --sample_metafile s3://scpca-references/example-data/example_sample_metadata.tsv \
  --celltype_project_metafile s3://scpca-references/example-data/example_project_celltype_metadata.tsv \
  --outdir s3://scpca-references/example-data/scpca_out \
  -with-tower
```

**Comment by sjspielman** [comment]
Interesting... I have relaunched with `project_celltype_metafile`, and look at this (partially copied) status:


```
[-        ] process > genetic_demux_sce                                   -
[80/90300e] process > post_process_sce (library01)                        [100%] 1 of 1, cached: 1 ✔
[ee/fd5522] process > cluster_sce (library01)                             [100%] 1 of 1, cached: 1 ✔
[-        ] process > annotate_celltypes:classify_singler                 -
[-        ] process > annotate_celltypes:classify_cellassign              -
[d0/94d9b9] process > annotate_celltypes:add_celltypes_to_sce (library01) [  0%] 0 of 1
[-        ] process > sce_qc_report                                       -
[-        ] process > sce_to_anndata:export_anndata                       -
[-        ] process > spaceranger_quant:spaceranger                       -
[-        ] process > spaceranger_quant:spaceranger_publish               -
```

Somehow the logic skipped `annotate_celltypes:classify_singler` and `annotate_celltypes:classify_cellassign`. `add_celltypes_to_sce` still says "submitted", so I will come back and update this comment when we learn the error.

**Comment by jashapiro** [comment]
> Somehow the logic skipped `annotate_celltypes:classify_singler` and `annotate_celltypes:classify_cellassign`. `add_celltypes_to_sce` still says "submitted", so I will come back and update this comment when we learn the error.

That's probably because I ran it last night... So it is properly skipping!

**Comment by sjspielman** [comment]
> That's probably because I ran it last night... So it is properly skipping!

Oh..!! I see now timestamps in the `scpca_out` directory for 1:24 am, and indeed now the progress has moved onto `sce_qc_report`. Going to kill it now and instead confirm output you generated looks right 👍

**Comment by sjspielman** [comment]
Noting that `anndata` and `SCE` files look as expected 🎉

**Comment by allyhawkins** [comment]
Just a reminder that part of this should include updating the `scpca_out.zip` file that's on S3 since that's where the link in the docs leads to.

**Comment by sjspielman** [comment]
`scpca-out.zip` updated with latest version ✅
