### ISSUE TITLE
Update celltype reference building to better track reference versions

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#470]
We've discussed strategies for tracking whether cell typing might need to be repeated in the main workflow. One aspect to track is versions of the cell typing references. We track panglao's version as the _date_ embedded in the reference filename (essentially our copy of the database):
https://github.com/AlexsLemonade/scpca-nf/blob/3c8a0b1ff84d493bb5a239a0b56712a0a5a2d0ee/config/reference_paths.config#L24

We should also record a package version for celldex. Look through the code now, we really don't have an equivalent celldex file to that panglaodb file for recording this information, since celldex is of course just there in an R package, not a stand-alone TSV. 

I see two overall kinds of approaches here:

1. We should actually get the version info into the specific _model/marker gene files_. For example:
    - `cellassign_references/PanglaoDB-blood.tsv` --> `cellassign_references/PanglaoDB-27_Mar_2020-blood.tsv` 
    - `singler_models/BlueprintEncodeData_model.rds` --> `singler_models/BlueprintEncodeData-<celldex version>-model.rds`

2. Or, modify the `celltype_ref_source` column in https://github.com/AlexsLemonade/scpca-nf/blob/3c8a0b1ff84d493bb5a239a0b56712a0a5a2d0ee/references/celltype-reference-metadata.tsv to be in the format `method_version`, e.g. `panglaodb-27_Mar_2020` and `celldex_<version>`.  Or, we could add a `celltype_ref_version` column with the version info. 

Tagging @allyhawkins @jashapiro for thoughts/discussion!

**Comment by allyhawkins** [comment]
I think we should modify the `celltype_ref_source` column to include the versions as you suggested in 2. But then I think we should also include the versions in the reference files that get output. That way the reference version is captured in the filename and we can use that to check for repeating cell typing.

**Comment by jashapiro** [comment]
> * `cellassign_references/PanglaoDB-blood.tsv` --> `cellassign_references/PanglaoDB-27_Mar_2020-blood.tsv`

Please use ISO8601:
`cellassign_references/PanglaoDB-blood_2020-03-27.tsv`

Also: I (following Jenny Bryan) prefer to use `-` to separate words, `_` for "fields". We maybe haven't used this 100% consistently, but I'm trying.
So probably: `singler_models/BlueprintEncodeData_<celldex version>_model.rds`

I also think adding a separate column for version info in the metadata table makes sense. My understanding was that `celltype-reference-metadata.tsv` is used only for the input to the reference generation workflow, and is independent of the main workflow.

Which is to say: I think we do #2, which is fed into the script to _also_ do #1?

**Comment by sjspielman** [comment]
> Please use ISO8601:

💯 I think the reason we haven't been is that we were matching how PanglaoDB records this, but we are allowed to not do that and instead do it right!

**Comment by jashapiro** [comment]
Just noting we will need to update internal instructions after we have implemented this, as noted here: https://github.com/AlexsLemonade/scpca-nf/pull/500#discussion_r1355668763 after we

**Comment by allyhawkins** [comment]
Note that when we address this, we will also want to make sure we update `celltype_qc.rmd` to properly pull out the organ type from the file name. Right now we assume the files are named with `<database><organ>` but that may not be the case once we address this. 
See https://github.com/AlexsLemonade/scpca-nf/pull/528#discussion_r1376490396

**Comment by allyhawkins** [comment]
From our meeting today, we would like to make the following changes: 

- Grab the `celldex` package version in the `save_singler_refs.R` script and include the package version in the saved reference file. 
- Grab the date for PanglaoDB from the file name for the PanglaoDB reference file. 
- Update all reference files to be formatted like so: 
	- SingleR: `<ref_name>_<source>_<version>_model.rds`
	- CellAssign: `<ref_name>_<source>_<version>.tsv`

FigJam for reference: https://www.figma.com/file/XFUxtxjZob6MnRtWLMLlOD/Cell-type-reference-tracking?type=whiteboard&node-id=0-1&t=5Vh375LWcaZaHmeB-0

**Comment by sjspielman** [comment]
Question about this, relevant to some docs I'm starting shortly - 

From the figjam notes, we decided to add version information into the meta json:

> store version and source as variables in scpca-meta.json - human readable is good

But, I neither see nor recall any decision we made about storing version information in the _SCE metadata_, something like `celldex_version` and `panglao_version`... does anyone else see or recall, or if also neither, what thoughts do we have about it? @allyhawkins @jashapiro 

For context, here's what the SCE metadata currently is storing re-cell typing:

https://github.com/AlexsLemonade/scpca-docs/blob/4dbb2d698e0be9bb4e3b4e003f3dc74ad14a64c7/docs/sce_file_contents.md?plain=1#L135-L140

**Comment by allyhawkins** [comment]
I think we just need to add `singler_reference_version` and `cellassign_reference_version` to the SCE metadata. I think that should be part of #538

**Comment by sjspielman** [comment]
It seems to me the only thing left to do here is captured separately in https://github.com/AlexsLemonade/scpca-nf/issues/549, and I think we can close this out now since it was broken up.
@allyhawkins, what do you think?
