### ISSUE TITLE
Add command line argument to set seed in `filter_sce_rds.R`

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#48]
Based on discussion in #45 and in the scpca meeting, we will want to make sure we set a seed for reproducibility of steps that occur in the `filter_sce_rds.R` script, in particular use of `emptyDrops` inside `scpcaTools::filter_counts()` and implementation of `miQC`. To do this we can add in a command line argument for the filtering script to set the seed and put in a default value for that seed. This will then set the seed in the global environment and allow us to use the seed for the steps occurring in the filtering script. 

One remaining question is if we want to include the seed as a nextflow parameter or not allow that flexibility to control the seed and leave it as the default for the argument added to `filter_sce_rds.R`.

**Comment by jashapiro** [comment]
closed by #50
