### ISSUE TITLE
Rethink SingleR process

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#485]
While working towards the process to add celltypes to the SCE as part of #415, I found some spots where I think we need to rethink:

- First, I don't think we need to export a separate TSV file of annotations if we're already exporting the _whole_ singler result object! That information is all in the full object, and there's no need for a separate file. Seems more efficient to just retain the DataFrame and grab what we need from it when adding to SCE.

- Second, we need to retrieve some deleted information SingleR process & R code. Originally I removed this code that maps ontology labels to cell types names since that process was no longer adding to the SCE; I figured I'd bring that code back for the add celltypes process: https://github.com/AlexsLemonade/scpca-nf/blob/b20fcb1174686e73ad3857b7e01e98ff86f83697/bin/classify_SingleR.R#L92-L110
  However, this code _requires_ having access to the singler model file - `singler_model$cell_ontology_df`. There are two immediate ways I can think of to handle this:
  - Make `singler_model_file` an input to the add celltypes process (and necessarily the label name)
  - Or, _do not cancel_ the separate TSV file for singler annotations as I suggested above, but instead keep it and do the ontology/cell names mapping in the classify singler script. Then, the TSV will have this mapping taken care of and and we can simply join it into the coldata. I think I prefer this option?

- A related point is that we could also consider _enforcing_ using `label.ont` reference labels with SingleR, but this makes me nervous in case we end up having to use something other than celldex one day. Currently this is just a default workflow parameter.

CC @jashapiro

**Comment by jashapiro** [comment]
I think I would favor keeping the tsv as well, and having the ontology id and ontology label passed along that way. 

One other option is to add `singler_model$cell_ontology_df` to `metadata(singler_results)` and passing it along that way. I think that is likely better than passing along the original model object, which could be large.

I think in general I am in favor of both? Having the ontology dataframe in the singler result object makes for easier input, but I like having the tsv available for debugging/flexibility.

**Comment by sjspielman** [comment]
Closed by #490
