### ISSUE TITLE
Add flag perform_celltyping

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#494]
_Related to #415_

By default, we do not want to perform cell typing. We should include a flag `perform_celltyping` with a default of `false` (or the inverse, `skip_celltyping` with a default of `true`), and then use an if statement to govern whether to enter into the celltypes process at all.

Figjam for reference: https://www.figma.com/file/9zH1gXlz9ZlxVrndN4Wy54/cell-type-workflow?type=whiteboard&node-id=0-1&t=fKgV0qjgpXfOkmFo-0

**Comment by jashapiro** [comment]
It is easy to have a default of `false` and have it set to `true` by the presence of the flag with no arguments, as we do with the flags here: https://github.com/AlexsLemonade/scpca-nf/blob/67e175bdbbfb314e0870a1b832d48001bfa87d9e/nextflow.config#L35-L39

I don't _think_ the reverse works, but I'm relying on old memories.

**Comment by allyhawkins** [comment]
Just noting from our discussion that this should be implemented in the main workflow as the `perform_celltyping` flag should be applied to all libraries. 

Something like: 
```
if(params.perform_celltyping){
  annotated_celltype_ch = annotate_celltypes( cluster_sce.out )
} else {
 // make sure the channel has the same structure as the output of running cell type annotation
  annotated_celltype_ch = cluster_sce.out.map{}
}
```

**Comment by sjspielman** [comment]
When implementing this feature, note there are a few spots that will need to be updated to use this parameter with the comment: `// TODO: add params.perform_celltyping && (...)  when implemented` in `modules/qc-report.nf`. These TODOs were left for future doing in #496.
