### ISSUE TITLE
Main report - Fix bugs and formatting in cell type tables

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#512]
We found a few bugs/ issues with formatting of the cell type tables that need to be addressed: 

- [ ] `NA` in submitter annotations should be "Unclassified cell" 
- [ ]  Make order of tables based on percentage of cells annotated as each cell type. Keep Unknown/ Unclassified cells as last row 
- [ ] Present the cell ontology labels rather than cell ontology term ids for the `SingleR` table

While working on this, it might be a good idea to account for submitters using something similar to unclassified cells with their annotations. If we can, we want to avoid two rows that both refer to unclassified cells.

**Comment by sjspielman** [comment]
Noting this existing related issue `Standardize how we refer to unknown cell types` https://github.com/AlexsLemonade/scpca-nf/issues/454

**Comment by allyhawkins** [comment]
Closed by #528
