### ISSUE TITLE
Update cell type report to account for multiplexed samples 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#519]
Once we have made the necessary changes to the cell type report for regular single-cell/single-nuclei samples, we will want to account for displaying cell type annotations in multiplexed samples. 

- We should include a warning that these are multiplexed samples. We have one at the top of the main report, but we might add a note in the cell type section to remind users. We should also include the warning in the supplemental report. 
- We may want to either remove the cluster comparison or re-structure it to account for each sample in the multiplexed library. 

I'm sure there are other things that I am missing, but we should use this issue to track any changes we might want to make when accounting for multiplexed cell type annotations. Then we can break out into additional issues if necessary.

**Comment by sjspielman** [comment]
As discussed in DSTM - 

- Add warning to the top (make sure all the celltype reports get it!)
- Remove heatmap showing cluster comparison
- Add additional warning at UMAP colored by cluster

**Comment by sjspielman** [comment]
One quick clarification if someone can weigh in @allyhawkins @jashapiro ?

For this - 
> Add warning to the top (make sure all the celltype reports get it!)

I'm assuming I meant to write here top of the _cell type section of each report_ (vs the whole report)? Especially we already have a warning of some kind at the top of the whole thing here - https://github.com/AlexsLemonade/scpca-nf/blob/74b744b8ba978d1745df17a7834d04e451d09fae/templates/qc_report/main_qc_report.rmd#L142-L155

**Comment by sjspielman** [comment]
Closed by #574
