### ISSUE TITLE
Firm up some QC report language

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#530]
How should we refer to cell type methods as a phrase itself, e.g. "Cell type annotation method"? "Cell typing method"?

Feel free to comment in this issue with other phrases you notice we need to solidify! CC @jashapiro @allyhawkins

**Comment by allyhawkins** [comment]
I'm going to vote we use "Cell type annotation" throughout.

**Comment by sjspielman** [comment]
Noting that I also am shifting wording in the supplemental report to "cell type **annotation**" and not "cell type **assignment**", where applicable. See some of those changes here - https://github.com/AlexsLemonade/scpca-nf/pull/535/commits/6114f615a711af7d8761ed362a057acde96d5520

**Comment by sjspielman** [comment]
When "inventorying" this text, also compare back to `scpca-portal` docs and ensure consistent language.

**Comment by sjspielman** [comment]
Spots to consider fixing:

- `assignment` -> `annotation` https://github.com/AlexsLemonade/scpca-nf/blob/9a47fb05689e9475d3bede44c46ecea496533d2d/internal-instructions.md?plain=1#L125
- A couple uses of `cell type label` in the supplemental QC report can be changed to `cell type annotation`, but I don't really think it's a problem. Sometimes we literally _are_ talking about labels in a way that somewhat differs from an annotation.

`scpca-portal` is as expected, uses only "annotation."

**Comment by sjspielman** [comment]
Made the change needed in #555, so this issue is effectively set once that goes in.

**Comment by sjspielman** [comment]
Closed by #555
