### ISSUE TITLE
Change reference names stored in reference metadata

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#537]
We have decided that `blood` or `muscle` is not totally reflective of what's included when building the PanglaoDB references. So we need to change the `ref_name` to be `<organ>_compartment` in the reference metadata file stored in `references`.

**Comment by jashapiro** [comment]
For later parsing of file names, it would be good to avoid `_`, so we should probably do `<organ>-compartment`

**Comment by allyhawkins** [comment]
Closed by #548
