### ISSUE TITLE
Improve approach for sizing heatmaps

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#541]
We have heatmaps in the supplemental cell type report, but the way we determine sizing still needs to be tweaked. We'll need to process more projects first to help us identify the right approach for general use.

**Comment by sjspielman** [comment]
Noting font size may also come into play: https://github.com/AlexsLemonade/scpca-nf/commit/07bf56a4fe7dcfdda5fef4b2d9ed7b7b2b0a82b2#r131828986

**Comment by allyhawkins** [comment]
I think we can close this since we looked at a bunch of reports and things looked good? @sjspielman

**Comment by sjspielman** [comment]
> I think we can close this since we looked at a bunch of reports and things looked good?

Yup, sounds good. We can always reopen if we encounter edge cases down the line!
