### ISSUE TITLE
Finalize celltype report text content

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#542]
We'll want to finalize text in the celltype report in a couple spots. Free check boxes for anything that is already finalized!

- [ ] Introduction
- [ ] Heatmap interpretation
- [ ] singler delta median sina plots
- [ ] cellassign probability density plots

**Comment by sjspielman** [comment]
Noting this PR focuses on conceptual content, but specific wording can be cleaned up in #530

**Comment by sjspielman** [comment]
Copying relevant issue text, #454:

> This was brought up by @allyhawkins in [#451 (review)](https://github.com/AlexsLemonade/scpca-nf/pull/451#pullrequestreview-1627139453) -
> 
> > [A]nother thought I had is related to how we are labeling "unclassified cells" vs "unknown cells". We should standardize this across methods probably.
> 
> Indeed, we should. Here's what we _currently_ have:
> ### Submitter
> 
>     * Cells that the submitter did not annotate at all are labeled as `NA`.
> 
>     * Cells that the submitter attempted to annotate but could not define are labeled as `"Unclassified cell"`
> 
> 
> ### `SingleR`
> 
>     * In the pruned labels, cells that could not be confidently annotated are labeled `NA`.
> 
>     * In the QC report, we show these in figures/tables as `"Unknown cell type"`.
> 
> 
> ### `CellAssign`
> 
>     * Cells that do _not_ have the marker genes are labeled as `"other"`.
> 
>     * In the QC report, we show these in figures/tables as `"Unknown cell type"`.

**Comment by sjspielman** [comment]
I've gone through all the text currently in the report, and flagged some spots that we could clean up and/or expand on a bit. For this, I just grabbed the main text parts of the report and annotated them with my thoughts.

Sharing here for any feedback before I get to implementing! Note that I've drawn some stars in spots where I've asked questions for what should we do, all in the quality assessment text sections. 

If you could have a look and let me know any  opinions by **EOD Wednesday 11/15** that would be great! Then I'll aim to file this on Thursday. @jashapiro @allyhawkins 

[Note Oct 31, 2023.pdf](https://github.com/AlexsLemonade/scpca-nf/files/13341036/Note.Oct.31.2023.pdf)

**Comment by allyhawkins** [comment]
I'm on board with Josh's suggestions, and have a few small ones: 

- Second sentence "this goal" should be "the goal"
- "one way to address this is to perform multiple cell type annotation approaches" should probably be "one way to address this is to use multiple cell type annotation approaches". 
- I think you can keep the delta median in italics, or just keep it as normal text. I would format Jaccard and delta median the same way, since they are both measurements.

**Comment by sjspielman** [comment]
> Probably could remove "rug" completely. Just say "blue line segments"?

All comments sound good, but wondering actually whether we want to say "blue" -  and similarly somewhere else where we say "red diamonds" maybe should just be "diamonds"? My reasoning is that CVD folks might not agree that these colors are blue and red, and the shapes are unique to the plots so color isn't _needed_ to describe the geom.

**Comment by sjspielman** [comment]
Closed by #568
