### ISSUE TITLE
Put the cell type section back

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#550]
In https://github.com/AlexsLemonade/scpca-nf/pull/547, we temporarily removed the child cell type report from getting called in the main report, in order to get `AnnData` out the door.

We'll need to put it back to for https://github.com/AlexsLemonade/scpca-nf/issues/544!

**Comment by sjspielman** [comment]
@allyhawkins given that this is closed https://github.com/AlexsLemonade/ScPCA-admin/issues/684, I can move to putting this celltype section back, right? Or do we need to wait for anything else?

**Comment by allyhawkins** [comment]
Correct. You are good to add this back in!

**Comment by sjspielman** [comment]
We get to close this for free!
https://github.com/AlexsLemonade/scpca-nf/pull/547 was done directly off of `main` **for the formerly-named version of this file** `qc_report.rmd`. This was done so that we wouldn't have to circle back and add it back in to the `development` version of this file now called `main_qc_report.rmd`. 

So.....closing!
