### ISSUE TITLE
Document the references directory

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#561]
`references/` really needs a README. 

This issue brought to you by me looking for some docs that I couldn't find.

**Comment by allyhawkins** [comment]
I would agree that we could use a README, but just FYI that a lot of the information related to what's in that folder is in `internal-instructions.md`. I think I would focus the README on external users that are looking at that folder and then link to the internal instructions for Data Lab members - https://github.com/AlexsLemonade/scpca-nf/blob/main/internal-instructions.md#maintaining-references-for-scpca-nf

**Comment by sjspielman** [comment]
Closed by #586
