### ISSUE TITLE
pre-commit foibles

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#566]
Opening this issue since I have fought my first fight with the pre-commit hook, which was _insisting_ on removing the **`Table of Contents`** label from the table of contents. So, this is a discussion-y sort of issue, and/or a place to collect thoughts about spots we could update the hooks.

The first time I went to commit, it did a bunch of restyling, most of which was good! But due to some unfortunate earlier tabbing spacing (4 spaces instead of 2), one of the long bulleted lists got de-bulleted and became one large paragraph. This was easy enough to fix on my own! Then for the next commit, it insistently deleted **`Table of Contents`**. See `git diff` screenshot - 
<img width="300" alt="Screenshot 2023-11-15 at 7 59 30 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/4701111/f82c95db-56a7-431f-973b-ac4786f07f89">

After 2-3 rounds of reinstating **`Table of Contents`** and hoping the pre-commit hook would magically stop forcing this upon me, I just ended up going with `git commit --no-verify` to doing any hook checks at all. This seemed fine for this circumstance since the styler had already been applied, but maybe there's a better way.

**Comment by sjspielman** [comment]
Yeah, it's upsetting the `doctoc` hook. The title is not forcibly removed if we include the full -  

**Table of Contents** _generated with [DocToc](https://github.com/thlorenz/doctoc)_

**Comment by sjspielman** [comment]
Noting I may have been to generous about the bullet situation. It's been changing my intended nesting left and right.... So my morning workflow has been:
- First a commit that calls the hook to style whatever it wants to style
- Then I fix whatever needs to be fixed manually
- Then I _actually_ commit with `--no-verify`

**Comment by jashapiro** [comment]
> Noting I may have been to generous about the bullet situation. It's been changing my intended nesting left and right....

It is very strict about following common mark I think... so blank lines before bullet lists and such are required. The other place I have seen it get picky is bullet lists within numbered lists. On my phone at the doctor, so I can't look up the full solution there.

**Comment by sjspielman** [comment]
>  The other place I have seen it get picky is bullet lists within numbered lists.

^ This is what I have been experiencing!

**Comment by jashapiro** [comment]
But if we decide it is too strict, we can look at the settings for prettier... pretty sure it can be made less aggressive or skip markdown entirely.

**Comment by sjspielman** [comment]
> Try adding --title='**Table of Contents**' to the args of the hook?

👍 but just `--title=**Table of Contents**` (no quotes)

**Comment by sjspielman** [comment]
Just noting also that I definitely understand the spirit behind table changes like this (`----` divider length below header matches text length in the table column), but the experience working with the table in `soft wrap` is...not great...
<img width="600" alt="Screenshot 2023-11-15 at 8 40 09 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/4701111/db59aa70-e091-4fba-80a6-7319631dce85">

**Comment by jashapiro** [comment]
> Just noting also that I definitely understand the spirit behind table changes like this (`----` divider length below header matches text length in the table column), but this user's experience working with the table in `soft wrap` is...not great... <img alt="Screenshot 2023-11-15 at 8 40 09 AM" width="600" src="https://user-images.githubusercontent.com/4701111/283133219-db59aa70-e091-4fba-80a6-7319631dce85.png">
> 
> **edit** - i am pleased to say this comment may have been disinformation... the hook just actually "fixed" one of these headers aka made it a much more reasonable length. Let's assume I was confused earlier and that the hook is doing nice things here!

I think this may still come up... the only option I see is to add `<!-- prettier-ignore -->` before the table, which should make it not try to reformat the table. The other way it can work is if we use an option to never wrap lines, but it seems like that would unwrap OSPL, so we don't want to do that.

**Comment by jashapiro** [comment]
> Noting I may have been to generous about the bullet situation. It's been changing my intended nesting left and right.... So my morning workflow has been:
> 
> * First a commit that calls the hook to style whatever it wants to style
> * Then I fix whatever needs to be fixed manually
> * Then I _actually_ commit with `--no-verify`

Just a note on this: we don't want this to become a habit, as what this does is put the same burden of work on everybody who edits the file in the future. If the `pre-commit` hooks are doing things we don't want, we need to modify them until they do what we want or disable them, not force people to work around them, as that really defeats the purpose.

**Comment by sjspielman** [comment]
> Just a note on this: we don't want this to become a habit, as what this does is put the same burden of work on everybody who edits the file in the future. If the pre-commit hooks are doing things we don't want, we need to modify them until they do what we want or disable them, not force people to work around them, as that really defeats the purpose.

:100: - I'll need to take some time and really think specifically on where the places to modify and/or disable are. 

Something else I just encountered but did not investigate was a situation where it kept telling me one of the hooks failed in the check, but nothing was ever changed in the file - so every `git commit` just led to the file being stuck "as is" with no staging. And, as before, it involved nested bullets.

**Comment by jashapiro** [comment]
> Something else I just encountered but did not investigate was a situation where it kept telling me one of the hooks failed in the check, but nothing was ever changed in the file - so every `git commit` just led to the file being stuck "as is" with no staging. And, as before, it involved nested bullets.

I'd definitely want to know what hook was failing and why for this! I don't think every hook fixes problems it finds, but they all should report why they failed.

**Comment by sjspielman** [comment]
sadly ive lost it... but will record here ASAP if it happens again!

**Comment by sjspielman** [comment]
@jashapiro Back in the same commit hole, again nested bullets inside a numbered list. I'm just directly attaching the version of the file I'm working with that is causing the problem. The failure of interest here is `prettier`.  If I keep running `git commit`, I end up in the same place every time - file ready to be committed but that I am unable to commit. 🦫 (this beaver is as close as I can get to :groundhog:)
 
[internal-instructions.md](https://github.com/AlexsLemonade/scpca-nf/files/13368432/internal-instructions.md)


<img width="1170" alt="Screenshot 2023-11-15 at 1 41 40 PM" src="https://github.com/AlexsLemonade/scpca-nf/assets/4701111/60fa8ffb-996e-467a-924b-88f0c057380e">

**Comment by jashapiro** [comment]
Ah... Looks like `doctoc` and `prettier` are fighting. I think `doctoc` is making a change that `prettier` is undoing. Try disabling prettier or move doctoc to after `prettier`? 

I am also not opposed to just disabling `prettier` on markdown files, which we can do with `exclude: '\.md$'` (or something like that) in the `prettier` hook.

**Comment by sjspielman** [comment]
Ok, over in https://github.com/AlexsLemonade/scpca-nf/pull/555 - 

- I tried swapping moving `doctoc` after `prettier`, no dice
- I was wary about wholesale removing `prettier`, so I tried excluding `md` - https://github.com/AlexsLemonade/scpca-nf/pull/555/commits/342b2464335ab1ae16893dffdad371e89e1d8289 - and we're good!! So, this is going to come in as part of #555 (or I can revert and get it in a standalone PR if really preferred).

**Comment by jashapiro** [comment]
No need for a separate PR, go for it where it works!

**Comment by sjspielman** [comment]
Things have been working pretty smoothly since this issue, so I'm going to close it since the discussion has ended. We can open a new issue if we uncover new foibles.
