### ISSUE TITLE
Add missing example files

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#570]
As submitter cell types are not necessary, we do not currently provide metadata examples in `examples/` for how to use them. In the future, we may want to add example files to show clearly how to provide your own cell type annotations as part of the workflow.

---

**Edit** - 

Noting this context from #571:
https://github.com/AlexsLemonade/scpca-nf/pull/571#issuecomment-1814755230

> >But, do we want to then create example_metadata_files/submitter_celltypes.tsv? I had had something for that in the external instructions PR that just went in - see this commit: [38dba37](https://github.com/AlexsLemonade/scpca-nf/commit/38dba37ba7d0321d4c046dc0d01bb7e7b3b4f9cb) . I can bring something like that file back.

> Seems worth having.

While this issue was originally opened to create `example_metadata_files/submitter_celltypes.tsv`, it seems that in [`example_run_metadata.tsv`](https://github.com/AlexsLemonade/scpca-nf/blob/619e638d10eef6de342639bf28f232d56ac3f5de/examples/example_run_metadata.tsv), we have several analogous files that don't exist. 

- `example_barcode_files/cite_barcodes.tsv`
- `example_barcode_files/cellhash_barcodes.tsv`
- `example_metadata_files/submitter_celltypes.tsv`

We should probably make them all if we're going to make one. This issue should track them all.

**Comment by sjspielman** [comment]
After some discussion in #571, we're headed there shortly!

**Comment by sjspielman** [comment]
Noting this context:
https://github.com/AlexsLemonade/scpca-nf/pull/571#issuecomment-1814755230

> >But, do we want to then create example_metadata_files/submitter_celltypes.tsv? I had had something for that in the external instructions PR that just went in - see this commit: [38dba37](https://github.com/AlexsLemonade/scpca-nf/commit/38dba37ba7d0321d4c046dc0d01bb7e7b3b4f9cb) . I can bring something like that file back.

> Seems worth having.


In [`example_run_metadata.tsv`](https://github.com/AlexsLemonade/scpca-nf/blob/619e638d10eef6de342639bf28f232d56ac3f5de/examples/example_run_metadata.tsv), we have some other analogous files that don't exist. 

We should probably make them all if we're going to make one - 

- `example_barcode_files/cite_barcodes.tsv`
- `example_barcode_files/cellhash_barcodes.tsv`
- `xample_metadata_files/submitter_celltypes.tsv`

**Comment by jashapiro** [comment]
Note that the barcode files are the same format, so we might not need both... Those are also a format determined by the tool, not our workflow. Which doesn't mean we shouldn't have them, but it is probably worth noting when linking to them. (I think/hope the docs already describe that)

**Comment by sjspielman** [comment]
After further discussion, we're going to instead point to documentation (in external instructions) for these example files in the examples README.

**Comment by sjspielman** [comment]
Closed by #588
