### ISSUE TITLE
Update external instructions celltype reference information

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#572]
After #502, we left some `TODO`s in the `external-instructions.md`:

https://github.com/AlexsLemonade/scpca-nf/blob/74b744b8ba978d1745df17a7834d04e451d09fae/external-instructions.md?plain=1#L361-L377

Currently #565 is establishing an approach to be able to quickly see all available models. We should update the instructions to point external users to those spots.

**Comment by jashapiro** [comment]
Noting that we can link to https://scpca-references.s3.amazonaws.com/celltype/singler_models/singler_models.tsv and https://scpca-references.s3.amazonaws.com/celltype/cellassign_references/cellassign_references.tsv for people to look up available cell type references.

**Comment by jashapiro** [comment]
closed by #573
