### ISSUE TITLE
Add example cell type metadata file

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#575]
I added this line to the external instructions, but did not add the example cell type project metadata file -  https://github.com/AlexsLemonade/scpca-nf/blob/619e638d10eef6de342639bf28f232d56ac3f5de/external-instructions.md?plain=1#L400-L401 .... Woops! We'll need that example file!

That said, I am actually wondering whether we should simplify the metadata files to just three columns: project id, singler file, and cellassign file. The `singler_ref_name` and `cellassign_ref_name` columns aren't actually used anywhere. We use the file names of course - 
https://github.com/AlexsLemonade/scpca-nf/blob/619e638d10eef6de342639bf28f232d56ac3f5de/modules/classify-celltypes.nf#L125-L135

But a `grep` of the repo shows that columns `singler_ref_name` and `cellassign_ref_name` are never used (plus that info is completely, and systematically!, encapsulated in the file name).

I would be in favor of removing name fields from the metadata file to make it a bit simpler to prepare. @allyhawkins @jashapiro, any thoughts on this?

**Comment by allyhawkins** [comment]
I think I would prefer to keep the `ref_name`. I think it's nice to have a more human readable version of the reference name. Also if we were to ever combine the tables (reference metadata and project cell type metadata), we would have that column to use.

**Comment by sjspielman** [comment]
> I think I would prefer to keep the `ref_name`.  I think it's nice to have a more human readable version of the reference name.

I am convinced!

**Comment by sjspielman** [comment]
Ah! When the rellink didn't work I assumed the file wasn't there. The file was there... just a bad link!
Going to pop this fix into #573.
https://github.com/AlexsLemonade/scpca-nf/blob/619e638d10eef6de342639bf28f232d56ac3f5de/examples/example_project_celltype_metadata.tsv
