### ISSUE TITLE
Move integration processes to a separate module

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#592]
We are planning to repurpose the existing workflow for integration to just be for merging objects. This means we no longer need the processes that perform integration via Harmony and fastMNN. Instead of delete those entirely, we plan to move these into a separate Nextflow module that will not currently be used. That way, if we ever do want to integrate, we will be able to use those processes.

**Comment by sjspielman** [comment]
Closed by #597
