### ISSUE TITLE
Repurpose current integration workflow for merging objects only 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#593]
We would like to edit the existing integration workflow, [`integrate.nf`](https://github.com/AlexsLemonade/scpca-nf/blob/main/integrate.nf) to only be used for merging objects and creating a summary report for those merged objects. Once we remove the integration processes (see #592), we should do the following: 

- [x] Rename the workflow to `merge.nf`
- [x] Remove the parameters for `integration_metafile` and `integration_group`. 
- [x] Group the library ids by `scpca_project_id` for merging. 
- [x] Temporarily remove rendering the integration report, since we will later turn that into a merged report

**Comment by sjspielman** [comment]
In #597, we renamed the workflow to `merge.nf`, and the code that runs the integration report process has been commented out.

**Comment by allyhawkins** [comment]
Closed by #605
