### ISSUE TITLE
Create an outline of the merged summary report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#594]
After we have merged objects, we will want to create a summary report that will be created along with the merged object. We don't quite yet know what this will look like, but we have a few ideas of what should be included: 

- Tables with the number of samples and/or libraries
- Tables that summarize clinical metadata for included libraries. E.g., how many of each disease, how many of each tissue type
- Lots of warnings that things aren’t integrated
- UMAPs of merged object
  - probably colored by library id
  - some projects have a lot of libraries, so how will we deal with lots of colors 

We should create an outline of what will go into the report and draw out what we would like it to look like, before tacking the report.

**Comment by sjspielman** [comment]
We have a plan for the merged report:

- Open with a _brief_ introduction:
  - Big yellow banner _caution this is not integrated._
  - State the project that has been merged
  - State that merged objects can be used for downstream analyses that jointly consider multiple samples, but caution that some downstream analyses may need batch-corrected data, and this object is not batch corrected.
- Section with tables
  - Sentence about we have # libraries and # samples
  - Several small tables for each of the following (at least):
    - Technology
    - Diagnosis, and subdiagnosis if present
    - Samples with ADTs
    - Multiplexed samples
    - Disease timing
- Section with UMAPs
  - Big yellow banner _caution this is not integrated._
  - Sentence explaining how the UMAPs were calculated (they are not the same as UMAPs in the individual-library objects)
  - Faceted UMAP with gray background points and a single color all around for library of interest
     - We should probably also state that each facet (below) is a _library, not a sample_, if the data is multiplexed
     - We'll also need to dynamically set the chunk plot size based on the number of libraries.

**Comment by sjspielman** [comment]
Now that we have a plan recorded for posterity, we can close this issue and track report progress in #624, #625, and #626.
