### ISSUE TITLE
Update colors used for cell type UMAPs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#612]
Right now, we are using the `Dark2` palette. However, the two greens that are showing up in this palette are a bit hard to distinguish from each other, which can make it hard to see which cell is assigned to which cell type. We should update the color palette that we use so it's easier to distinguish the cells on the plot. Maybe we could use `Okabe-Ito` instead?

**Comment by sjspielman** [comment]
Closed by #615
