### ISSUE TITLE
Support compressing AnnData objects

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#616]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/AlexsLemonade/scpcaTools/issues/244 should support 

**Describe the solution you'd like**
We should add compression to both
`bin/sce_to_anndata.R` and 
`bin/move_counts_anndata.py`

The former depends on https://github.com/AlexsLemonade/scpcaTools/issues/244, but the latter does not, and can be implemented with just a `compression` argument to [`AnnData.write`](https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.write.html). Unfortunately, we don't always run `move_counts_anndata.py`, so we can't just put compression there. 

**Describe alternatives you've considered**

We could make the compression in `sce_to_anndata.R` an argument, which might be useful so we don't waste time compressing processed data before we move the counts and recompress. 

**Additional context**
Just noting that we use `.hdf5` everywhere, but maybe we want to switch to `.h5ad`?

**Comment by allyhawkins** [comment]
Closed by #621
