### ISSUE TITLE
Aesthetic updates to miQC plots

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#620]
Idle thought: do we want to apply these aesthetic improvements to `scpca-nf` too?

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/CART_Monje/pull/173#discussion_r1426925647_

In the Monje workflow, we made some small adjustments to the lines printed on the miQC plots. We might consider adding those changes to the miQC plots in this repo.

**Comment by sjspielman** [comment]
Closed by #689
