### ISSUE TITLE
Test CPU usage for CellAssign

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#622]
We recently increased the number of CPUs and memory requested for running `CellAssign`. We want to do a test to make sure that when we do increase the number of CPUs, we decrease the run time. 

We are using `SCPL000015` to do this test. It's already been run with 24 CPUS and 96 GB at a run time of 4 h 16 min. 
We should also run with 32 CPUs and 128 GB and see if the run time decreases. When we do this remember to increase the `max.cpus` and `max.memory`.

**Comment by allyhawkins** [comment]
Just noting that the run time for 32 CPUs and 128 GB was 4 h 8 min. 

I will do another run with 12 CPUs and 64 GB.

**Comment by jashapiro** [comment]
So it seems that the 12/CPU/64GB version failed with an out of memory error. 

The 12 CPU/96GB version took ~5 h 6 min (second try with one spot instance kill). I would say that means we should probably run cellassign at that config, as the benefits of more CPUs are not likely to be worth the cost.

**Comment by allyhawkins** [comment]
I don't think that run actually finished? Tower doesn't show that CellAssign was completed since this message pops up. 

<img width="835" alt="Screenshot 2023-12-20 at 8 10 41 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/3af27cd1-8917-44f8-88db-289f0602746e">

**Comment by jashapiro** [comment]
Hmmm. According to AWS it completed with exit code 0. That error seems like a nextflow something that failed. Hopefully transient?

**Comment by allyhawkins** [comment]
Looking at the time stamps for the results and the checkpoints folder for that library, the last timestamp is 12/18. If it succeeded, there should have been a timestamp for a file on 12/19.

**Comment by jashapiro** [comment]
Yes, nextflow clearly failed to get the results and proceed, but the batch job itself seems to have succeeded. So I expect we can trust the timing. But It makes sense to test again... with 96 GB RAM.

**Comment by allyhawkins** [comment]
> Yes, nextflow clearly failed to get the results and proceed, but the batch job itself seems to have succeeded. So I expect we can trust the timing. But It makes sense to test again... with 96 GB RAM.

Okay I'll start that run now.

**Comment by allyhawkins** [comment]
Confirming that the 12 CPU/ 96 GB ran in 5 h 2 min, so we should update to use this config moving forward.

**Comment by allyhawkins** [comment]
I'm going to close this since we completed the test.
