### ISSUE TITLE
Merged report: Initiate report

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#624]
This issue tracks starting the merged report:

1) Make relevant changes in the workflow itself to render the report
2) Add the introductory section (_broken out of #594_):
   - Big yellow banner: caution this is not integrated!
   - Sentence about which project this is (this should also be reflected in the report's title)
   - State that merged objects can be used for downstream analyses that jointly consider multiple samples, but caution that some downstream analyses may need batch-corrected data, and this object is not batch corrected.

**Comment by allyhawkins** [comment]
Closed by #629
