### ISSUE TITLE
Mapping workflow should fail if mapping files are missing

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#639]
In the event that mapping files (fastq) are not present, then we need to make sure that any workflow run that is meant to include mapping should rather than potentially overwriting previous results.

We should first check the current behavior, making espeically sure that running with `--repeat-mapping` when there are no fastq files in the specified directory does not result in a blank output from alevin mapping steps. If this is not currently the case, we should modify the workflow to correct this.

**Comment by jashapiro** [comment]
Noting that the stub test files do not currently include input files for `STUBR16`, which can be used as a partial test case for implementation here: https://github.com/AlexsLemonade/scpca-nf/pull/630#issuecomment-1875637051

The processes for `STUBR16` should be skipped if the directory is missing or empty. `file()` does not check for presence by default, but adding that check after the fact should allow us implement this more safely here.

**Comment by sjspielman** [comment]
Closed with #649
