### ISSUE TITLE
Indicate cell line status in QC report

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#645]
We plan to skip cell type annotation on cell line samples. I wonder if we should also aim to include somewhere in the QC report that the particular sample is a cell line. For example, would we want a little info box that no cell typing was performed since it's a cell line? 

*Edited for typos

Opening this issue for future discussion, probably(?) next sprint (week of 1/15/24).

**Comment by sjspielman** [comment]
If we pursue this, we'll need to get `is_cell_line` into the meta map. 

From https://github.com/AlexsLemonade/scpca-nf/issues/650#issuecomment-1889873539:

>That said, we might want to pass along the cell line info in the metadata separately anyway, which we could do by adding a small amount of processing to update the meta object in sce_files_channel_branched.cell_line.
> Something like:
> ```
>  cell_line_ch = sce_files_channel_branched.cell_line.map{
>    def meta_out = it[0].clone()
>    meta_out.is_cell_line = true
>    [meta_out] + it.drop(1)
>  }
>```

**Comment by sjspielman** [comment]
After some Slack discussion, we have decided to **yes** include this information, and _also_ include it for xenografts!

We'd like to add a blue info box (`alert-primary`) to the top of the report, in the same spot where we add the multiplex info box. For xenografts, we'll just let them know it's a xenograft sample. For cell lines, we'll let them know it's a cell line _and_ therefore no cell type annotation was performed.

Since we're going to need to now pull 2 things out of the sample metadata, we'll want to think a little more about strategies for wrangling in the information since it can't just be in the `sce_files_channel_branched.cell_line` channel.

**Comment by jashapiro** [comment]
> Since we're going to need to now pull 2 things out of the sample metadata, we'll want to think a little more about strategies for wrangling in the information since it can't just be in the `sce_files_channel_branched.cell_line` channel.

I'd still do mostly the same thing: make a list of cell lines and a list of xenografts, then use a `map` with `if` statements to add to the `meta` object rather than branching. If you do that early (but preferably after mapping to prevent having to change the checkpoint data), you can use that in the `branch` as well.

**Comment by allyhawkins** [comment]
We have this documented in a different issue https://github.com/AlexsLemonade/scpca-nf/issues/663

**Comment by sjspielman** [comment]
> We have this documented in a different issue https://github.com/AlexsLemonade/scpca-nf/issues/663

🤦‍♀️ thank youuuu

**Comment by sjspielman** [comment]
> If you do that early (but preferably after mapping to prevent having to change the checkpoint data)

Looking at implementing this now, and just want to note that I think we do have to move cell line (and now incoming xenograft) code out of the celltype subworkflow, because we only go into that subworkflow if `params.perform_celltyping` is on. Regardless of this param, we'll want to indicate the sample type in the QC report.

Given this, I'm opening up a quick chat for how folks feel about also aiming to get this information into the SCE in the first place; for example, something like `metadata(sce) <- <"cell line"/"patient-derived xenograft"/"patient tissue">`, in the `generate_unfiltered_sce` area of the code. @allyhawkins @jashapiro

**Comment by allyhawkins** [comment]
> Given this, I'm opening up a quick chat for how folks feel about also aiming to get this information into the SCE in the first place; for example, something like metadata(sce)$sample_type <- <"cell line"/"patient-derived xenograft"/"patient tissue">, in the generate_unfiltered_sce area of the code. @allyhawkins @jashapiro

Since we are already reading in the sample metadata in this script, then I would agree that this is a good place to add that information.

**Comment by sjspielman** [comment]
> Since we are already reading in the sample metadata in this script, then I would agree that this is a good place to add that information.

💯 fantastic point, this means we can leave the current nextflow code alone I think.

**Comment by sjspielman** [comment]
Closed with #667
