### ISSUE TITLE
Add instructions for running the merging workflow

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#646]
I noticed that we don't have any documentation on the `merge.nf` workflow. We might want to include that at minimum, in the internal instructions. 

We should probably also think about if we want to include a section in the external instructions?

**Comment by sjspielman** [comment]
Noting I'll pick up at least the internal instructions part!

**Comment by sjspielman** [comment]
In DSTM Pre-planning meeting on 1/16/24, we decided we would probably like to do this _before the paper_ goes out, but we don't need it for the cell type release.

**Comment by sjspielman** [comment]
External instructions have been written in #688, so all parts of this issue are set
