### ISSUE TITLE
Render celltype report only if library is not a cell line

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#650]
**Edit** - scope of issue is shifting to just cell lines, not submitters. Read on in comments!

Noticed a bug in `qc-report.nf` that we presumably haven't caught because we haven't encountered the condition that would cause the error - 

https://github.com/AlexsLemonade/scpca-nf/blob/6ec12a56c8336351df0c570e584c9780b45b22b2/modules/qc-report.nf#L28-L30

This code means that if there are _only submitter_ cell types, then there will not be a cell type report. We need to update this logic to - 

```
has_celltypes = meta.submitter_cell_types_file || (params.perform_celltyping && (meta.singler_model_file || meta.cellassign_reference_file))

**Comment by sjspielman** [comment]
We should also take this time to account for cell lines, for which we do not want a cell type report.

That said, there is always a chance that submitters give us a cell type file anyways, you never know...

**Comment by jashapiro** [comment]
> if there are _only submitter_ cell types, then there will not be a cell type report.

I thought this was what we wanted? If there are only submitter cell types, then most of the report is irrelevant, and _we_ didn't do anything, so our QC metrics mostly don't apply. I guess the only thing would be the overlap with clusters, and I don't feel very strongly about having that.

**Comment by sjspielman** [comment]
> I thought this was what we wanted? If there are only submitter cell types, then most of the report is irrelevant, and we didn't do anything, so our QC metrics mostly don't apply. I guess the only thing would be the overlap with clusters, and I don't feel very strongly about having that.

I don't specifically recall, but your argument is sound to me! Let's just rescope this issue to focus on the cell line logic.

**Comment by sjspielman** [comment]
The logic we have in there should work just fine for us, so we can close this out.
