### ISSUE TITLE
Fix bug in files_directory checking

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#670]
We have uncovered a bug related to changes that were previously made in 

Specifically, these lines fail altogether if the fastq's are gone (and they are now gone!)

https://github.com/AlexsLemonade/scpca-nf/blob/development/modules/af-rna.nf#L128
https://github.com/AlexsLemonade/scpca-nf/blob/development/modules/af-features.nf#L167

We'll want to first check that `it.files.directory` is `true` before this check happens.

**Comment by jashapiro** [comment]
Related, and we should probably fix at the same time:

In `bulk-salmon.nf`, `spaceranger.nf` and `genetic-demux.nf` we should update branching with the same pattern as `af-rna.nf` to prevent errors when raw data files do not exist.

**Comment by sjspielman** [comment]
Closed by #671. 

Noting this https://github.com/AlexsLemonade/scpca-nf/issues/670#issuecomment-1910462148 will get fixed as part of #672
