### ISSUE TITLE
Add missing_inputs branches to non-alevin mapping

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#672]
Related, and we should probably fix at the same time:

In `bulk-salmon.nf`, `spaceranger.nf` and `genetic-demux.nf` we should update branching with the same pattern as `af-rna.nf` to prevent errors when raw data files do not exist.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/scpca-nf/issues/670#issuecomment-1910462148_

Adding detail here that this means changing branches for skipping mapping or quantification to check for the existence of the files directory variable and contents, and allowing for a missing_inputs branch. These updates should include sending `missing_inputs` branches to the log, as is done in `af-rna.nf`

**Comment by allyhawkins** [comment]
Closed by #673
