### ISSUE TITLE
Add precommit ci to CONTRIBUTING.md

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#695]
I wonder if we also want to say something about `precommit-ci`, as either a separate or nested topic for `pre-commit hooks` in general, in the contributing file?

_Originally posted by @sjspielman in https://github.com/AlexsLemonade/scpca-nf/issues/694#issuecomment-1942088757_
            
---

Something to circle back to!

**Comment by jashapiro** [comment]
We don't say anything about the other CI checks, so we would probably want something that covered all of them.
