### ISSUE TITLE
Add sentence to cell type report indicating references come from normal samples

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#707]
> I think adding a sentence to the section on cell typing in the processing docs would be sufficient, or if we want to make sure users see it we could include it in the report itself.

both? Just a quick, "Please be aware that all cell type references include only normal (not tumor) tissue." would suffice, I think.

_Originally posted by @sjspielman in https://github.com/AlexsLemonade/ScPCA-admin/issues/716#issuecomment-1966685634_

**Comment by sjspielman** [comment]
Here's the version of this sentence we added to docs:
https://github.com/AlexsLemonade/scpca-docs/blob/53d4f79b863688e6fab289d5e83d30db813f66dc/docs/processing_information.md?plain=1#L87

**Comment by allyhawkins** [comment]
Closed by #725
