### ISSUE TITLE
[BUG] CellAssign process getting killed with `OutOfMemoryError`

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#709]
**Describe the bug**
If you have an error message or report that you can include, please do!

In running SCPCP000016 through `scpca-nf` with cell typing, I'm consistently getting the same error stating that the task was killed due to being out of memory. This project does use the all pediatric cancer reference, which is not used by any other projects that have been processed, so I do wonder if that's part of it. 

I've tried bumping up the memory to 256 and get the same error everytime. I will note that one library did complete successfully but it has ~500 cells, whereas the other libraries have > 7,000 cells. 

**To reproduce**
If possible, please provide example code to reproduce the problem, including any information about the dataset where the problem occurred, if possible.

The following command but specifying the prod `outdir` and the project: 

`nextflow run AlexsLemonade/scpca-nf -r v0.7.2 -profile ccdl,batch --perform_celltyping`

**Additional context**

This is the main message that Nextflow has for the error: 
```
The exit status of the task that caused the workflow execution to fail was: 137

Error executing process > 'annotate_celltypes:classify_cellassign (SCPCL000835)'

Caused by:
  Essential container in task exited - OutOfMemoryError: Container killed due to memory usage
```

Then here's the output error message from running `CellAssign`: 

```
Command error:
  Warning message:
  replacing previous import ‘S4Arrays::makeNindexFromArrayViewport’ by ‘DelayedArray::makeNindexFromArrayViewport’ when loading ‘SummarizedExperiment’ 
  Registered S3 methods overwritten by 'zellkonverter':
    method                                             from      
    py_to_r.numpy.ndarray                              reticulate
    py_to_r.pandas.core.arrays.categorical.Categorical reticulate
  miQC_model cannot be converted between SCE and AnnData.
  /usr/local/lib/python3.10/dist-packages/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
    self.seed = seed
  /usr/local/lib/python3.10/dist-packages/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
    self.dl_pin_memory_gpu_training = (
  Global seed set to 2021
  No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
  /usr/local/lib/python3.10/dist-packages/scvi/data/fields/_base_field.py:64: UserWarning: adata.X does not contain unnormalized count data. Are you sure this is what you want?
    self.validate_field(adata)
  GPU available: False, used: False
  TPU available: False, using: 0 TPU cores
  IPU available: False, using: 0 IPUs
  HPU available: False, using: 0 HPUs
  /usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py:281: PossibleUserWarning: The number of training batches (5) is smaller than the logging interval Trainer(log_every_n_steps=10). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
    rank_zero_warn(
  
  Training:   0%|          | 0/400 [00:00<?, ?it/s]
  Epoch 1/400:   0%|          | 0/400 [00:00<?, ?it/s].command.sh: line 9:  1141 Killed                  predict_cellassign.py --input_hdf5_file "processed.hdf5" --output_predictions "SCPCL000835_cellassign/cellassign_predictions.tsv" --reference "pediatric-cancers_PanglaoDB_2020-03-27.tsv" --seed 2021 --threads 12
```

**Comment by jashapiro** [comment]
Definitely looks like a memory issue. I think with the current setup we have, we can use up to 488GB memory, but I could reconfigure the compute modules to use different instance types with greater memory. In particular, we are currently using C4, M4, and R4 instances, but if we added in R5 or R5a we could go to 768 or R6a to go to 1536. 

I suspect this is a change we should make anyway, as the 5 and 6 series instances may be more efficient at this point, and apparently are interrupted less, if something I read online is to be believed.

**Comment by allyhawkins** [comment]
> Definitely looks like a memory issue. I think with the current setup we have, we can use up to 488GB memory, but I could reconfigure the compute modules to use different instance types with greater memory. In particular, we are currently using C4, M4, and R4 instances, but if we added in R5 or R5a we could go to 768 or R6a to go to 1536.
> 
> I suspect this is a change we should make anyway, as the 5 and 6 series instances may be more efficient at this point, and apparently are interrupted less, if something I read online is to be believed.

Okay, good to know about the max being 488. I went ahead and submitted a run with that to see if that's enough. Hopefully!

**Comment by jashapiro** [comment]
I added new instance types, so we should be able to go to ~1.5TB memory. But hopefully it doesn't take that. Make sure you update both the memory request for the process and the `max_memory` param

**Comment by allyhawkins** [comment]
Alright, so I bumped up the `max_memory` param and am using `mem_488` in the process for classifying CellAssign, but when I run the workflow tower is showing me that `max_memory` is still set to `256`. 
The changes I'm trying to run are on `allyhawkins/cell-assign-mem-bump` and I've made sure to re-pull that branch and check that the workflow that is cached has `max_memory=488`. I feel like there might be some other limitation on the queue that we are using?

**Comment by allyhawkins** [comment]
For some additional context, it looks like the process is using `c6a.48xlarge` which has a max memory of 384 GiB.

**Comment by jashapiro** [comment]
See #711 for a suggestion: it looks like you changed one `max_memory`, but  not the one in use for the `ccdl` profile.

> For some additional context, it looks like the process is using `c6a.48xlarge` which has a max memory of 384 GiB.

This is good news as it means the AWS changes I made did get applied properly!

**Comment by allyhawkins** [comment]
I just wanted to note that I'm testing a sample using the `mem_512` label, and it's on its third attempt and has been for a little over a day. I'm hoping that it completes by tomorrow, and if it does, we should identify how we want to handle requesting this much memory for these samples. I'm assuming that we don't want to just increase the initial memory request to 512 for all libraries... 

Also this library is currently attempting to use 1 TB, so we probably want the capability to increase memory to that much. One thought I had was to create a separate label only used for the CellAssign process that starts at the initial 96 GB, but increases to maybe 500 on the second attempt and then 1 TB by the third retry? This would mean requesting more memory for samples that probably don't need that much on a third retry. 

Another option would be to only increase the memory to 500 and 1 TB, if the exit status was a memory error. @jashapiro do you have any other ideas or preference on what we do here?

**Comment by jashapiro** [comment]
One option is to have a `mem_max` label that just goes right to `params.max_memory`, but keep the max_memory in the param file something sane. Then when calling the workflow you could add `--max_memory "1.TB"` or similar when running those samples.

**Comment by allyhawkins** [comment]
> One option is to have a `mem_max` label that just goes right to `params.max_memory`, but keep the max_memory in the param file something sane. Then when calling the workflow you could add `--max_memory "1.TB"` or similar when running those samples.

I like this idea. You mean to replace the current `mem_96` label with a `mem_max` label that goes to the max memory on the first retry?

**Comment by jashapiro** [comment]
> You mean to replace the current mem_96 label with a mem_max label that goes to the max memory on the first retry?

I actually meant right from the start! But giving one shot at something large but not necessarily the max would be fine.
