### ISSUE TITLE
Adjust output of ST module to reflect desired output files

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#71]
After quantification with Spaceranger, we will want to reorganize the output files to only publish those that we are going to be user facing. Right now the workflow includes publishing the entirety of the `outs` folder from Spaceranger, which we will not need. We can adjust the workflow to only include the output files mentioned in https://github.com/AlexsLemonade/scpca-nf/issues/68#issuecomment-998926142. We should then include all of the files below as one zip file before publishing the files as part of the process in Nextflow. 

Originally posted in https://github.com/AlexsLemonade/scpca-nf/issues/68#issuecomment-998926142. 

> After our discussion today in the ST benchmarking meeting, we have decided to use Spaceranger and provide the outputs from Spaceranger as a zip file. We should include the unfiltered and filtered output from Spaceranger, the web summary (equivalent to our qc report), the spatial folder, and a metadata file that we would add in with version information. This is approximately what the contents of the download for each library would then look like for the ST libraries.

```
├── SCPCL000000_filtered_files
│   ├── barcodes.tsv.gz
│   ├── features.tsv.gz
│   └── matrix.mtx.gz
├── SCPCL000000_spaceranger_summary.html
├── SCPCL000000_spatial
│   ├── aligned_fiducials.jpg
│   ├── detected_tissue_image.jpg
│   ├── scalefactors_json.json
│   ├── tissue_hires_image.png
│   ├── tissue_lowres_image.png
│   └── tissue_positions_list.csv
├── SCPCL000000_unfiltered_files
│   ├── barcodes.tsv.gz
│   ├── features.tsv.gz
│   └── matrix.mtx.gz
└── SCPCL00000_metadata.json
```

**Comment by jashapiro** [comment]
Linking to my comment in the other issue:
https://github.com/AlexsLemonade/scpca-nf/issues/68#issuecomment-998940420
