### ISSUE TITLE
Ideas for reducing file sizes

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#710]
**Is your feature request related to a problem? Please describe.**

Our files are pretty big, especially RDS files. We could save storage and download space with some smallish changes.

**Describe the solution you'd like**

A simple and transparent to users change would be to change our RDS compression from gzip to bzip2. This can be implemented with a change in `write_rds()` from `compress='gz'` to `compress='bz2'`, and will be completely transparent to users as far as code goes, as the result is still an `rds` file

In my testing, this takes about 50% longer (e.g. 35 seconds vs 21 seconds, though so not much really), but results in files ~50% smaller. However, the read time increases substantially, from ~1.4 to 9.4 seconds in the example I tested. I tend to think the tradeoff is likely worth it for our use case, but others may disagree, so we should discuss this!

**Describe alternatives you've considered**

One other idea I had was to remove the `miQC_model` object from the "processed" files. At that point, the data in the object can't really be used as the rejected cells have already been removed. This object is also fairly large (100MB or more) and does not appear to compress well, so removing it would save a significant amount of space, and having it in both the "filtered" and "processed" data seems redundant. This change would require a docs update as well.
 
I also tested `xz` compression, but this was _much_ slower, on the order of 4 minutes for the same file as above, with similar compression to `bz2` (a bit smaller). It did read about 2x as fast as bz2 though. Something about all this doesn't seem quite right, and may be to do with the implementation of xz in R, but it is what it is.

**Comment by jashapiro** [comment]
Tagging @allyhawkins, @sjspielman and @jaclyn-taroni  for comments

**Comment by allyhawkins** [comment]
> In my testing, this takes about 50% longer (e.g. 35 seconds vs 21 seconds, though so not much really), but results in files ~50% smaller. However, the read time increases substantially, from ~1.4 to 9.4 seconds in the example I tested. I tend to think the tradeoff is likely worth it for our use case, but others may disagree, so we should discuss this!

My concern would be read time for the larger merged objects, not necessarily the smaller individual objects. I think at least for the individual RDS files then this proposal makes sense. 

> One other idea I had was to remove the miQC_model object from the "processed" files. At that point, the data in the object can't really be used as the rejected cells have already been removed. This object is also fairly large (100MB or more) and does not appear to compress well, so removing it would save a significant amount of space, and having it in both the "filtered" and "processed" data seems redundant. This change would require a docs update as well.

I'm totally onboard with removing it from the processed objects.

**Comment by sjspielman** [comment]
> My concern would be read time for the larger merged objects, not necessarily the smaller individual objects. I think at least for the individual RDS files then this proposal makes sense.

Good middle ground!

**Comment by jashapiro** [comment]
closed by #712
