### ISSUE TITLE
Add is_xenograft & is_cell_line to example metadata

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#713]
We need `is_xenograft` and `is_cell_line` columns here: https://github.com/AlexsLemonade/scpca-nf/blob/development/examples/example_sample_metadata.tsv

They are expected here:
https://github.com/AlexsLemonade/scpca-nf/blob/1569842882eadc5a378f5eba51759cde9241ad3d/bin/generate_unfiltered_sce.R#L182-L190

**Comment by sjspielman** [comment]
> They are expected here:

That said, we should also either:

- Add checks that those columns are present for a more informative error if they are missing
- Handle this differently if either of those columns is missing. For example, we could default to `"patient tissue"` if a value isn't specified.

**Comment by allyhawkins** [comment]
> > They are expected here:
> 
> That said, we should also either:
> 
> * Add checks that those columns are present for a more informative error if they are missing
> * Handle this differently if either of those columns is missing. For example, we could default to `"patient tissue"` if a value isn't specified.

I think I would actually favor just setting those columns to `NA` if they are missing. If they aren't provided, I don't think it should kill the workflow or that we should fill them in by default. 
We could print a message and then just use `NA`.

**Comment by sjspielman** [comment]
> I think I would actually favor just setting those columns to NA if they are missing. 

You mean in the R script itself? This seems like a good plan to me. In this case, we'd want to make sure that `sample_types` ends up as `NA` if values are `NA`. There would also not be anything printed here, which seems fine: https://github.com/AlexsLemonade/scpca-nf/blob/b400776085938e9bbc5e7062cffc1e0fa1fd2044/templates/qc_report/main_qc_report.rmd#L136 

We'd also want to update docs that this value can be `NA`: https://github.com/AlexsLemonade/scpca-docs/blob/aa3887cdd3d0ab8ea31b618b57d77f731b5a951a/docs/sce_file_contents.md?plain=1#L138

**Comment by allyhawkins** [comment]
> > I think I would actually favor just setting those columns to NA if they are missing.
> 
> You mean in the R script itself? This seems like a good plan to me. In this case, we'd want to make sure that `sample_type` ends up as `NA` if values are `NA`. There would also not be anything printed here, which seems fine:
> 
> https://github.com/AlexsLemonade/scpca-nf/blob/b400776085938e9bbc5e7062cffc1e0fa1fd2044/templates/qc_report/main_qc_report.rmd#L136
> 
> We'd also want to update docs that this value can be `NA`: https://github.com/AlexsLemonade/scpca-docs/blob/aa3887cdd3d0ab8ea31b618b57d77f731b5a951a/docs/sce_file_contents.md?plain=1#L138

Yes, this is what I was thinking. Or we can say "Not provided", if we want to be more clear about it, but either way I don't think we should automatically populate it with `patient tissue`.

**Comment by allyhawkins** [comment]
Closed by #725
