### ISSUE TITLE
Create nextflow_schema.json file

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#714]
**Is your feature request related to a problem? Please describe.**

Automatic argument parsing for cavatica uses the nextflow_schema.json file following the nf-core schema

**Describe the solution you'd like**

Create and add the file!

We should be able to do this with the `nf-core schema build` command. See https://nf-co.re/tools#pipeline-schema

**Comment by allyhawkins** [comment]
Closed by #720
