### ISSUE TITLE
Fix column name typos

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-nf#717]
Should be all lowercase `id`:
https://github.com/AlexsLemonade/scpca-nf/blob/fcf766cc6656f9f90d3b96fa0ae2a6ad8c05b46e/bin/merge_sces.R#L226-L227

**Comment by jashapiro** [comment]
This is intentional, because those are the column names from the original tool.

**Comment by sjspielman** [comment]
If these are the expected column names, then something else may be wrong since these columns are in the most recently-run merged object.  It also implies our docs are wrong:

https://github.com/AlexsLemonade/scpca-docs/blob/53d4f79b863688e6fab289d5e83d30db813f66dc/docs/merged_objects.md?plain=1#L328-L332

https://github.com/AlexsLemonade/scpca-docs/blob/53d4f79b863688e6fab289d5e83d30db813f66dc/docs/sce_file_contents.md?plain=1#L319-L323

**Comment by jashapiro** [comment]
No, I'm wrong, thinking about somewhere else!

**Comment by allyhawkins** [comment]
Closed by #719
