### ISSUE TITLE
Add sample metadata table to QC and cell type reports

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#765]
**Is your feature request related to a problem? Please describe.**

See https://github.com/AlexsLemonade/scpca-portal/issues/759

**Describe the solution you'd like**

We would like to include a sample metadata table in the main QC report. This should be included along with the processing and library tables that are currently present and should include things like: 

- sample ID
- diagnosis
- subdiagnosis 
- tissue location 
- age 
- sex
- disease timing

We want to include any sample metadata that is consistently collected across samples. 

**Additional context**

We might consider adding in the ontology IDs here as well. We will also have to make sure we account for things being NA as some samples do have missing information.

**Comment by allyhawkins** [comment]
Just noting that we should include this same table in both the main and cell type reports.

**Comment by jaclyn-taroni** [comment]
I changed the title to reflect https://github.com/AlexsLemonade/scpca-nf/issues/765#issuecomment-2176490048.

**Comment by allyhawkins** [comment]
As I started working on this, there were two things that came up that I think could benefit from asynchronous discussion: 

- What fields do we want to include in the table, specifically do we want to include ontology IDs and human readable values? 
- How do we want the table to look for multiplexed libraries. We could break up the table into individual sample metadata tables for each sample in the library or create a table with all samples? I think I would favor including all samples in one table, but we should probably consider how it would look for libraries that have 4-6 samples. 

Here's an example of what the table would look like with multiple samples for reference: 
<img width="337" alt="Screenshot 2024-06-28 at 10 58 01 AM" src="https://github.com/AlexsLemonade/scpca-nf/assets/54039191/8379f40d-096a-4c1e-a2cc-4f1c2e26b035">

**Comment by allyhawkins** [comment]
To summarize our discussion in pre-planning, we will not include ontology IDs, but may include a link to the ontology ID if it's not too big of a lift. 
For multiplexed samples, we are not going to provide sample information but instead a blue box indicating that no sample metadata is provided because the library has samples that have been multiplexed.

**Comment by allyhawkins** [comment]
Closed by #769
