### ISSUE TITLE
Add genetic demultiplexing workflow

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#80]
The genetic demultiplexing workflow currently implemented in https://github.com/AlexsLemonade/alsf-scpca/tree/main/workflows/genetic-demux should be integrated into the main scpca-nf workflow. 

If possible, this may reuse the STAR index created for Cell Ranger, rather than requiring a separate addition to `build-index.nf`.

**Comment by allyhawkins** [comment]
Closed by #93.
