### ISSUE TITLE
Make spaceranger process optional 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-nf#81]
Because the spaceranger step is very costly and takes a long time to run, we should incorporate the option to skip this step (similar to how we skip the production of the rad file in alevin-fry). In doing this, we should break out the file reorganization into it's own process so the first process is running spaceranger and the second process is file re-organization and creating the `metadata.json`.

**Comment by jaclyn-taroni** [comment]
My suspicion is that GitHub was having issues when #134 went in. Closing this!
