### ISSUE TITLE
Create 0.2.0 release

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#89]
With the addition of  #78, #77, #84, #85 and  (pending) #87, we have made a number of pretty big changes to the workflow (especially the step-skipping of #77 and #87) , and this seems to me to justify a bump up to version 0.2!

We will want to make this version update/release before we do the bulk mapping, as we want those metadata to reflect a real release.

**Comment by jashapiro** [comment]
@allyhawkins If there are any other issues that you think might block this release, please let me know in a comment and/or add them as dependencies above!

**Comment by allyhawkins** [comment]
I think this looks good and that we are good for the new release once we have #87 merged.

**Comment by jashapiro** [comment]
Done! https://github.com/AlexsLemonade/scpca-nf/releases/tag/v0.2.0
