### ISSUE TITLE
Make genetic demultiplexing optional

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-nf#95]
Genetic demultiplexing is a slow and expensive process, as it requires full alignment and SNP calling in multiple bulk samples and each multiplexed library. So we should have the ability to skip it if it has already been completed for a particular library.

To do this we can follow the patterns of https://github.com/AlexsLemonade/scpca-nf/pull/77 and https://github.com/AlexsLemonade/scpca-nf/pull/87. 

While it might be nice to save the intermediate alignments to save the most costly step, unfortunately that is not a good option, as those alignments will contain patient genetic data that we do not want to keep long term. So we will be limited to repeating the whole genetic demultiplexing process in an all-or-none fashion. I expect we will want to make that a separate flag from the normal mapping: I can imagine we might want to remap RNA with a new salmon version, but don't want to do a full realignment with STAR.

**Comment by allyhawkins** [comment]
Closed by #102.
